### PR TITLE
Enable dbus stop

### PR DESCRIPTION
**Pull request by baude**
Add the ability to be able to stop a container via dbus.

### CODE REVIEW

**Comment by baude** [comment]
[(2) [Dbus] Add support for atomic stop](https://trello.com/c/qp0GUEZq/240-2-dbus-add-support-for-atomic-stop)

**Comment by rhatdan** [comment]
How does the caller know what to set in extra-args?

**Comment by baude** [comment]
@rhatdan same discussion.  I am just keeping the in and out args the same.  So do you want to remove it here too? Just on the client side?

**Comment by rhatdan** [comment]
Yes I don't want extra-args passed across dbus.  Just hard code it on the server side to []

**Comment by baude** [comment]
Rebased and fixed.

**Comment by baude** [comment]
@rhatdan should be ready

**Comment by baude** [comment]
@rh-atomic-bot r+  	d72d04a

**Comment by baude** [comment]
@rh-atomic-bot retest

**Comment by cgwalters** [comment]
@rh-atomic-bot retry

**Comment by ashcrow** [comment]
The failure links seem wrong to me ... they are leading back to the commits.

**Pull request closed without merging**
