### PR TITLE
[merged] Fix crash on handling atomic containers delete --all

### PR DESCRIPTION
**Pull request by rhatdan**

### CODE REVIEW

**Comment by rhatdan** [comment]
@baude PTAL

**Comment by baude** [comment]
lgtm

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Comment by rhatdan** [comment]
@rh-atomic-bot retry

**Comment by rhatdan** [comment]
@jlebon @cgwalters 
Is rh-atomic-bot broken?

**Comment by jlebon** [comment]
@rhatdan Seems like the bot is down. http://escher.verbum.org:54856/ is no longer responding.
In the meantime, feel free to merge manually if it is time critical and the tests are passing.

**Comment by cgwalters** [comment]
@rh-atomic-bot r+ 5b405fa

**Pull request closed without merging**
