### PR TITLE
Atomic/util.py: Check install against FQ name

### PR DESCRIPTION
**Pull request by baude**
## Description

In cases where a short-hand name is provided to run and the image
was installed under its fq_name, we should check againt the
fq_name as well when determining if it has been installed.

## Related Issue Numbers
- #995 
-

## Pull Request Checklist:

If your Pull request contains new features or functions, tests are required. If the PR is a bug fix and no tests exist, please consider adding some to prevent regressions.
- [ ] Unittests
- [ ] Integration Tests

### CODE REVIEW

**Comment by miabbott** [comment]
A quick sanity check of `atomic run` with/without a tag worked for me

**Comment by baude** [comment]
@rh-atomic-bot bot, retest this please

**Comment by TomSweeneyRedHat** [comment]
Other than the tests failing, the change LGTM.  Are there any test cases/paths that should be added for this?

**Comment by baude** [comment]
bot, retest this please

**Comment by baude** [comment]
bot, retest this please

**Comment by rhatdan** [comment]
@rh-atomic-bot r+ 99c5e3b

**Comment by dustymabe** [comment]
re-attempt this merge?

**Comment by baude** [comment]
@rh-atomic-bot  	0b4a491

**Comment by baude** [comment]
@rh-atomic-bot r+ 0b4a491

**Pull request closed without merging**
