### PR TITLE
syscontainers: use XDG_DATA_HOME instead of XDG_DATA_DIR

### PR DESCRIPTION
**Pull request by giuseppe**
Adapt to the change of location in podman and buildah.

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
Changes LGTM, but the tests aren't happy.

**Comment by giuseppe** [comment]
there are a few pending PRs in atomic that are blocked on the centos test.  This won't be solved until the updated Skopeo will hit CentOS (it is already present on Fedora).  Should we manually merge these PRs?

**Comment by rhatdan** [comment]
Lets give it today, to get Centos Fixed.

**Comment by giuseppe** [comment]
rebased on top of the CI fixes

**Comment by giuseppe** [comment]
@rh-atomic-bot retry

**Pull request closed without merging**
