### PR TITLE
[merged] .redhat-ci.yml: enable homu-related branches

### PR DESCRIPTION
**Pull request by jlebon**
Also test auto and try branches.

### CODE REVIEW

**Comment by rhatdan** [comment]
@cgwalters PTAL

**Comment by cgwalters** [comment]
@rh-atomic-bot r+ 32ec91b

**Comment by cgwalters** [comment]
RE the CI failure, why are we running pip instead of using package dependencies?

**Comment by jlebon** [comment]
Yeah, will probably do that. The error above is: https://github.com/eliben/pycparser/issues/151, which is apparently breaking a lot of builds.

**Pull request closed without merging**
