### PR TITLE
[merged] Trust reset

### PR DESCRIPTION
**Pull request by aweiteka**

### CODE REVIEW

**Comment by rhatdan** [comment]
Can you fix the breakin tests.

I think you need. 

```
diff --git a/Atomic/util.py b/Atomic/util.py
index 0ebc559..f86f4b0 100644
--- a/Atomic/util.py
+++ b/Atomic/util.py
@@ -746,7 +746,7 @@ def is_insecure_registry(registry_config, registry):
 def is_valid_uri(uri, qualifying=None):
     try:
         import urllib2
-        urlparse = urllib2.urlparse.urlparse
+        urlparse = urllib2.urlparse.urlparse #pylint: disable=no-name-in-module,import-error
     except ImportError:
         import urllib.parse
         urlparse = urllib.parse.urlparse # pylint: disable=E1101
```

**Comment by aweiteka** [comment]
Might need a rebase after #822, depending on which comes first.

**Comment by rhatdan** [comment]
I have merged 822, so rebase after that gets merged.

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
