### PR TITLE
We are not calling self.cmd_env just passing the function

### PR DESCRIPTION
**Pull request by rhatdan**
This actually calls the function to setup the environment.

### CODE REVIEW

**Comment by rhatdan** [comment]
@baude PTAL

**Comment by baude** [comment]
@rhatdan I left those as they were originally defined, which was as a property.  See https://github.com/projectatomic/atomic/blob/1bc38149cd1aa3ac9bab6507ec42401f27ce9df3/Atomic/atomic.py#L500 as an example.

**Comment by rhatdan** [comment]
Well if this is the way it was done, before, I believe it is wrong, since it would be setting the environment to a function pointer.  I think we should merge this and test.

**Comment by rhatdan** [comment]
I am merging this to fix the issues with Environment.

**Pull request merged**
