### PR TITLE
Do not print docker command for atomic scan without verbose

### PR DESCRIPTION
**Pull request by hhorak**
When running atomic scan  --json, docker command is printed on stdout,
which makes the JSON output invalid:

```
#> atomic scan <img> --json >/tmp/out.json
#> cat /tmp/out.json
docker run -t --rm -v /etc/localtime:/etc/localtime -v /run/atomic/2017-02-24-13-29-15-255245:/scanin -v /var/lib/atomic/openscap/2017-02-24-13-29-15-255245:/scanout:rw,Z -v /etc/oscapd:/etc/oscapd:ro rhel7/openscap oscapd-evaluate scan --no-standard-compliance --targets chroots-in-dir:///scanin --output /scanout
{
    "Vulnerabilities": [],
    "Time": "2017-02-24T13:29:18",
    "Scanner": "openscap",
    "CVE Feed Last Updated": "2017-02-24T06:10:03",
    "UUID": "/scanin/95064c8c85af597c35a18b2581555c1e1a8640c72dd96551c43699ade9b398ea",
    "Successful": "true",
    "Finished Time": "2017-02-24T13:29:23",
    "Scan Type": "CVE"
}
```

This change only prints the docker command when --verbose or --debug options
are used.

### CODE REVIEW

**Comment by rhatdan** [comment]
bot, add author to whitelist

**Comment by rhatdan** [comment]
We should change the code to never print the command if the user has specified --json output.

**Comment by rhatdan** [comment]
Perhaps conflict --json with --display or --verbose.

**Comment by hhorak** [comment]
Sounds good, will change the PR to behave like this..

**Comment by rhatdan** [comment]
Thanks I like it.

@rh-atomic-bot r+ dd65254

**Comment by rhatdan** [comment]
@rh-atomic-bot r+ b986af5

**Comment by jlebon** [comment]
@rh-atomic-bot retry

**Comment by jlebon** [comment]
@rh-atomic-bot retry

**Pull request closed without merging**
