### PR TITLE
syscontainers: some improvements for the copy to the host case

### PR DESCRIPTION
**Pull request by giuseppe**
Print what files are copied to the host and handle Ctrl-C during install

### CODE REVIEW

**Comment by giuseppe** [comment]
@yuqi-zhang could you please take a look?

**Comment by yuqi-zhang** [comment]
LGTM, only minor question is why 7bd2a2 and ded0419 seems to add/remove the same part of code?

**Comment by giuseppe** [comment]
I think only the indentation was changed as I moved more code under the `try/except` block

**Comment by yuqi-zhang** [comment]
Oh sorry, it was a duplicate check and unlink. LGTM then.

**Comment by giuseppe** [comment]
@rh-atomic-bot delegate=yuqi-zhang

**Comment by yuqi-zhang** [comment]
@rh-atomic-bot r+ ddacca4

**Pull request closed without merging**
