### PR TITLE
tests/storage: only umount /dev/vdb if needed 

### PR DESCRIPTION
**Pull request by giuseppe**
Alternative version of: https://github.com/projectatomic/atomic/pull/1106

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
@rhvgoyal PTAL

**Comment by jlebon** [comment]
FWIW, I updated the original PR with a clearer commit message! See: https://github.com/projectatomic/atomic/pull/1106#discussion_r143614748.

**Comment by giuseppe** [comment]
Closing this since @jlebon is following up in the original PR

**Pull request closed without merging**
