### PR TITLE
Make the tests pass

### PR DESCRIPTION
**Pull request by jlebon**
This patch series makes some fixes so that the tests pass again.

PR #198 was merged with the tests failing. This caused the PRs that followed to also be marked as failures, thus potentially hiding any new failures. On the plus side, these failures have also helped uncover a few issues with the testing infrastructure, which should now all be resolved.

Hopefully, the auto-tester will like this PR. Once master passes again, PRs that are rebased should get a clearer picture of whether things passed or failed and why.

### CODE REVIEW

**Comment by jlebon** [comment]
@rhatdan @shishir-a412ed PTAL

**Comment by jlebon** [comment]
Nice, thanks @rh-atomic-bot! :punch:

**Comment by jlebon** [comment]
Updated PR. Addressed @cgwalters's comments and also decided to give a whack at replacing those `subprocess` calls to not use the shell.

**Comment by cgwalters** [comment]
Looks pretty good to me!  Thanks a lot for cleaning this up.  :+1:

**Comment by rhatdan** [comment]
BTW @jlebon great work, thanks for cleaning this up.

**Comment by jlebon** [comment]
Thanks @cgwalters and @rhatdan!

**Pull request merged**
