### PR TITLE
Coding Convention: E251 unexpected spaces around keyword / parameter equals

### PR DESCRIPTION
**Pull request by tuxdna**
This is a minor fix for coding conventions.

### CODE REVIEW

**Comment by rhatdan** [comment]
bot, add author to whitelist

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
bot, test pull request

**Comment by tuxdna** [comment]
@rhatdan thanks for adding me to whitelist :-) This would hopefully be my first accepted PR to project atomic.

**Comment by rhatdan** [comment]
@tuxdna You seem to have two pull requests in their can you remove the excess patch, and I will merge.

**Comment by tuxdna** [comment]
@rhatdan I rebased my fork and now it shows only one commit. I believe that is what you meant by excess patch.

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
