### PR TITLE
[merged] scan: fix regression in scan

### PR DESCRIPTION
**Pull request by giuseppe**
issue introduced with 4fbe2dc592ef620ffa35334edadc5dccca9029fb

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by giuseppe** [comment]
@baude does it fix the issue you reported?

**Comment by baude** [comment]
@giuseppe yes sir, ill merge.

**Comment by baude** [comment]
@rh-atomic-bot r+

**Comment by jlebon** [comment]
@rh-atomic-bot retry

**Comment by jlebon** [comment]
well-be-right-back-well-be-right-back-monkey-whall-org

**Comment by AmartC** [comment]
I have been working on scan as well for atomic_dbus.py and I saw that when I have the line m.args = self.args instead of calling m.set_args(self.args), then it works for both calling through the terminal and through DBus API.

**Comment by jlebon** [comment]
@rh-atomic-bot retru

**Comment by jlebon** [comment]
@rh-atomic-bot retry after you're done retruing

**Pull request closed without merging**
