### PR TITLE
[merged] Cleanup help information on containers

### PR DESCRIPTION
**Pull request by rhatdan**

### CODE REVIEW

**Comment by rhatdan** [comment]
Should fix https://bugzilla.redhat.com/show_bug.cgi?id=1380848

**Comment by rhatdan** [comment]
@baude PTAL

**Comment by baude** [comment]
lgtm

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Comment by rhatdan** [comment]
@rh-atomic-bot retry

**Comment by rhatdan** [comment]
@jlebon We seem to be stuck?

**Comment by rhatdan** [comment]
@cgwalters can you restart jenkins?

**Comment by cgwalters** [comment]
@rh-atomic-bot r+ 568f15c

**Pull request closed without merging**
