### PR TITLE
[merged] docs/atomic-sign.1.md: fix lost command

### PR DESCRIPTION
**Pull request by chuanchang**
Signed-off-by: Alex Jia <ajia@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Comment by chuanchang** [comment]
@rhatdan , it seems the patch hasn't been merged.

**Comment by rhatdan** [comment]
@rh-atomic-bot retry

**Comment by rhatdan** [comment]
This is broken, via conflicts Opened https://github.com/projectatomic/atomic/pull/611 to fix it.

**Pull request closed without merging**
