### PR TITLE
syscontainers: Fix rename with directories

### PR DESCRIPTION
**Pull request by giuseppe**
## Description

We saw some issues while using `renameFiles` with directories.  This PR addresses these problems

### CODE REVIEW

**Comment by ashcrow** [comment]
Pulled locally to verify it renamed directories and it does properly.

**Comment by giuseppe** [comment]
@rh-atomic-bot delegate=ashcrow

Since it is useful for the Docker container, if the series is fine for you, I think we can merge it

**Comment by ashcrow** [comment]
@rh-atomic-bot r+

**Comment by giuseppe** [comment]
it seems that Homu hangs when the commit is not specified, trying again:

@rh-atomic-bot r=ashcrow 57971cb

**Pull request closed without merging**
