### PR TITLE
Atomic/util.py: Add no_proxy

### PR DESCRIPTION
**Pull request by ashcrow**
## Description
Adds ``no_proxy`` to the proxy configuration.

## Related Bugzillas
- https://bugzilla.redhat.com/show_bug.cgi?id=1450310

### CODE REVIEW

**Comment by ashcrow** [comment]
@rhatdan PTAL

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by rhatdan** [comment]
Can you add a commit message, any chance we can get a test added for this?

**Comment by ashcrow** [comment]
@rhatdan sure and sure. Will do now.

**Comment by ashcrow** [comment]
@rhatdan done

**Comment by TomSweeneyRedHat** [comment]
Especially LGTM now with the added test and commit msg.

**Comment by baude** [comment]
@rh-atomic-bot r+  	279f772

**Pull request closed without merging**
