### PR TITLE
[merged] update: refactor into non-base verbs

### PR DESCRIPTION
**Pull request by yuqi-zhang**
Refactor:
  `atomic update`
  `atomic update --container`
  `atomic update --container --rollback`

To:
  `atomic images update`
  `atomic containers update`
  `atomic containers rollback`

And update corresponding tests, docs and auto-complete. Much like
other image commands (info, verify), the base verb is hidden but
still available for use.

Signed-off-by: Yu Qi Zhang <jerzhang@redhat.com>

### CODE REVIEW

**Comment by yuqi-zhang** [comment]
Currently this does not differentiate storage, and does not use backendutils. If anyone feels that `atomic update` -> `atomic images update` is unwarranted, I have a separately prepared commit that modifies just the container commands.

**Comment by baude** [comment]
@yuqi-zhang would you be willing to adopt the new refactoring code for backends and objects for new code you touch? It would help in the long run if more people used the code.  Not a requirement but just asking.

**Comment by yuqi-zhang** [comment]
Sure, I can do that as a separate PR.

**Comment by rhatdan** [comment]
Do we want to get this one merged, or should this be closed and replaced with a new pull request?

**Comment by yuqi-zhang** [comment]
I'm fine with refactoring to the new backendutils as a separate PR or as a commit on this. What do you think @baude @giuseppe

**Comment by rhatdan** [comment]
@yuqi-zhang Please Rebase.

**Comment by yuqi-zhang** [comment]
Rebased. Seems to be some permission issues with tests.

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
