### PR TITLE
atomic.conf: fix syntax error of the YAML format

### PR DESCRIPTION
**Pull request by chuanchang**
We use YAML format in atomic.conf file, so it should be KEY: VALUE
not KEY=VALUE.

Signed-off-by: Alex Jia <ajia@redhat.com>

## Related Bugzillas
-
-

## Related Issue Numbers
-
-

## Pull Request Checklist:

If your Pull request contains new features or functions, tests are required. If the PR is a bug fix and no tests exist, please consider adding some to prevent regressions.
- [ ] Unittests
- [ ] Integration Tests

### CODE REVIEW

**Comment by yuqi-zhang** [comment]
LGTM

**Comment by baude** [comment]
how about a super simple integration test that would actually test the default conf file we deliver to make sure it is valid YAML?

**Comment by ashcrow** [comment]
@baude I'll submit a test as a follow up to this.

**Comment by ashcrow** [comment]
https://github.com/projectatomic/atomic/pull/1009

**Comment by baude** [comment]
@rh-atomic-bot r+  	6014d9f

**Pull request closed without merging**
