### PR TITLE
[merged] add option to support automatically answer yes for all questions

### PR DESCRIPTION
**Pull request by chuanchang**
sometimes, I wanna delete importing directory automatically w/o interaction. 

Signed-off-by: Alex Jia <ajia@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
I would prefer that we do like dnf and make a flag be assume yes.

```       -y, --assumeyes
              Automatically answer yes for all questions
```

That way we can handle any future questions.

**Comment by rhatdan** [comment]
bot, add author to whitelist

**Comment by chuanchang** [comment]
@rhatdan , I simply added '--assumeyes' option into atomic import command, it had better we have a global class/function to manage command/command option like dnf, in order to implement this, we probably need to re-factoring codes, maybe, we can do this later.

**Comment by rhatdan** [comment]
We could add --assumeyes at the level of -v, --version and --debug to the atomic command.  Then you could do 

atomic -y storage export ...

**Comment by chuanchang** [comment]
@rhatdan, done, thanks for your review.

**Comment by rhatdan** [comment]
bot, add author to whitelist

**Comment by rhatdan** [comment]
Now I need updated man page and bash completion.  While you are fixing the man page can you add documentation for --debug and --version.  Thanks, then I can merge.

**Comment by chuanchang** [comment]
@rhatdan , done.

**Comment by rhatdan** [comment]
Awesome thanks.
@rh-atomic-bot r+

**Pull request closed without merging**
