### PR TITLE
When running atomic commands we need to pass the users environment

### PR DESCRIPTION
**Pull request by rhatdan**
The run and install commands were not seeing the environment, this will
allow users to pass environment variables into atomic commands.

### CODE REVIEW

**Comment by rhatdan** [comment]
@cgwalters @ari could you take a look at this.

**Comment by arilivigni** [comment]
LGTM this will be extremely helpful!

**Comment by cgwalters** [comment]
Otherwise looks like a nice cleanup to me, so :+1: with the above change.

**Comment by miabbott** [comment]
This appears to address #49.  Can it be closed?

**Pull request merged**
