### PR TITLE
Run args should include /bin/sh

### PR DESCRIPTION
**Pull request by rhatdan**

### CODE REVIEW

**Comment by rhatdan** [comment]
@baude I think this fixes the issue.

atomic run fedora

Is supposed to work.

**Comment by rhatdan** [comment]
https://bodhi.fedoraproject.org/updates/FEDORA-2017-b677c4a509

**Comment by jlebon** [comment]
Is that what we want though? Shouldn't we just let docker pick up the default CMD?

**Comment by rhatdan** [comment]
This change is wrong, problem is deeper in the code.

**Comment by rhatdan** [comment]
jlebon, there is no default command, but maybe you are right.  Perhaps we should look for command or entrypoint inside of the image and then fall over to /bin/sh

**Comment by rhatdan** [comment]
@jlebon ^^ @baude ^^

Bottom line is we need to get back to what we had before.

**Pull request closed without merging**
