### PR TITLE
PEP8 (Python style guide) Compliance

### PR DESCRIPTION
**Pull request by willmtemple**
Cleanup of python codebase to be compliant with [PEP8](https://www.python.org/dev/peps/pep-0008/), the style guide for python code, according to the `pep8` python code linter.

Signed-off-by: William Temple <wtemple@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
Did you use a tool to do this?  Or just the linter.

**Comment by willmtemple** [comment]
@rhatdan Just the linter. There are some automated tools out there like `pyfmt`, in the same vein as Golang's `gofmt`, but from testing it it, it doesn't seem mature. As of now, it recombines lines that are intentionally split for readability into single lines. IMHO a fatal flaw.

The `pep8` linter seemed to be the best fit, as `pylint` is, by default, _very_ agressive.

**Comment by willmtemple** [comment]
@rhatdan Example pyfmt output: https://github.com/willmtemple/atomic/commit/701bb1f4875e440788e9b5730770c9e31c970de3

**Comment by rhatdan** [comment]
I am fine with this.  @cgwalters Opinion?

**Comment by rhatdan** [comment]
Could you rebase this pull request.

**Comment by willmtemple** [comment]
@rhatdan Done.

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
