### PR TITLE
[merged] syscontainers: fix tarfile import with no RepoTags

### PR DESCRIPTION
**Pull request by giuseppe**
Fix import from a tarball when the manifest from Skopeo does not
specify the RepoTags.  In that case use the name given as input by
the user.

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by giuseppe** [comment]
@rh-atomic-bot retry

**Comment by rhatdan** [comment]
Needs a rebase.

**Comment by giuseppe** [comment]
just pushed now ⬆️

**Comment by giuseppe** [comment]
@rh-atomic-bot retry

**Comment by giuseppe** [comment]
some tests are failing on fetching for Docker hub

@rh-atomic-bot retry

**Comment by giuseppe** [comment]
@rhatdan is this PR good to merge?

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
