### PR TITLE
Add dbus integration test for install and uninstall

### PR DESCRIPTION
**Pull request by baude**

### CODE REVIEW

**Comment by baude** [comment]
[(3) [Dbus] Add support for atomic uninstall](https://trello.com/c/xkfEvvx5/243-3-dbus-add-support-for-atomic-uninstall)

**Comment by baude** [comment]
[(3) [Dbus] Add support for atomic install](https://trello.com/c/Ca2xDnHa/268-3-dbus-add-support-for-atomic-install)

**Comment by baude** [comment]
@rhatdan ready for merge

**Comment by rhatdan** [comment]
@rh-atomic-bot r+ 609a9ce

**Comment by rhatdan** [comment]
@baude Rebase and then merge.

**Comment by baude** [comment]
@rh-atomic-bot retry

**Comment by baude** [comment]
bot, retest this please

**Comment by baude** [comment]
@rh-atomic-bot r+ c46981d

**Pull request closed without merging**
