### PR TITLE
correct parameter name for InstallData exception

### PR DESCRIPTION
**Pull request by TomasTomecek**
In this case, `id` is the built-in function:

```
ValueError: Unable to find <built-in function id> in installed image data (/var/lib/atomic/install.json). Re-run command with -i to ignore
```

Signed-off-by: Tomas Tomecek <ttomecek@redhat.com>

### CODE REVIEW

**Comment by giuseppe** [comment]
@rh-atomic-bot r+ 68fe7eb

**Comment by TomasTomecek** [comment]
The CI failure is not caused by the PR:

```
+ systemctl restart docker
Failed to restart docker.service: Unit docker.service not found.
### EXITED WITH CODE 5 AFTER 2s
```

**Comment by giuseppe** [comment]
@TomasTomecek I've opened a PR to address it: https://github.com/projectatomic/atomic/pull/991

**Comment by TomSweeneyRedHat** [comment]
The change LGTM, but I'm not sure what's up with the test.  I concur that it's not related to this change.

**Comment by giuseppe** [comment]
@TomasTomecek please rebase, should fix the CI failure

**Comment by TomasTomecek** [comment]
rebased

**Comment by giuseppe** [comment]
@rh-atomic-bot r+ ca0fbc4

**Pull request closed without merging**
