### PR TITLE
[merged] bugfix in trust discovery and image parsing

### PR DESCRIPTION
**Pull request by aweiteka**
@baude please review

Fixes reported issues for atomic pull:

- bug `AttributeError: 'Namespace' object has no attribute 'sigstoretype'`
- bug `ValueError: need more than 1 value to unpack`
- python 2 bug writing registries.d config file with unicode strings "!!python/unicode ..."

### CODE REVIEW

**Comment by baude** [comment]
lgtm with rebase

**Comment by aweiteka** [comment]
> lgtm with rebase

done. waiting on test

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Comment by baude** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
