### PR TITLE
Migrate script should now work since we are after docker-1.10

### PR DESCRIPTION
**Pull request by rhatdan**

### CODE REVIEW

**Comment by rhatdan** [comment]
@shishir-a412ed PTAL

**Comment by rhatdan** [comment]
Looks like the migrate script needs some work.

**Comment by shishir-a412ed** [comment]
@rhatdan Yes this should work now. Let me test it with docker 1.10 and confirm.

Shishir

**Comment by rhatdan** [comment]
I want it tested with docker-1.12 also.  The test is blowing up now.  See Details

**Comment by jlebon** [comment]
The tester was still at 1.9, just updated it to 1.10.
Long-term I'd like to try migrating the testers to AH and let them auto-update.

**Comment by jlebon** [comment]
bot, retest this please

**Comment by jlebon** [comment]
The error is now:

```
Error response from daemon: empty export - not implemented
```

**Comment by shishir-a412ed** [comment]
@rhatdan I have opened a follow up PR #498  for this. Please check that.
We can close this one, and merge that one instead.

**Pull request closed without merging**
