### PR TITLE
Replace docker-storage-setup with container-storage-setup.

### PR DESCRIPTION
**Pull request by shishir-a412ed**
Signed-off-by: Shishir Mahajan <shishir.mahajan@redhat.com>

### CODE REVIEW

**Comment by shishir-a412ed** [comment]
ping @rhatdan

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Comment by rhatdan** [comment]
@rh-atomic-bot r+ 26a3d55

**Comment by shishir-a412ed** [comment]
@rhatdan Don't think the CI Failures are related to the PR.

**Comment by shishir-a412ed** [comment]
@rhatdan Any updates on this one ?

**Comment by rhatdan** [comment]
I think we want to remove this reference altogether and make atomic execute container-storage-setup itself.

**Comment by shishir-a412ed** [comment]
@rhatdan oh yeah ..we are reverting to the old behavior. I will close this PR and open another one for rollback.

Shishir

**Pull request closed without merging**
