### PR TITLE
trust, sign: prevent gpg warnings to be printed

### PR DESCRIPTION
**Pull request by giuseppe**
I've noticed this warning while using "atomic trust show":

gpg: WARNING: no command supplied.  Trying to guess what you mean ...

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
Will this eat real errors?  Should we not do this when setting the --debug flag?

**Comment by giuseppe** [comment]
I've changed it to redirect stderr to /dev/null only when --debug is not used

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by rhatdan** [comment]
@giuseppe did you verify that the message comes out when  you pass in the debug flag?  If so then 
LGTM

**Comment by giuseppe** [comment]
yes, I've verified it:

```
# ./atomic trust show
* (default)                         accept                               
registry.access.redhat.com          signed security@redhat.com,security@redhat.com https://access.redhat.com/webassets/docker/content/sigstore

# ./atomic --debug trust show
* (default)                         accept                               
gpg: WARNING: no command supplied.  Trying to guess what you mean ...
registry.access.redhat.com          signed security@redhat.com,security@redhat.com https://access.redhat.com/webassets/docker/content/sigstore
```

@rh-atomic-bot r=rhatdan

**Pull request closed without merging**
