### PR TITLE
[merged] atomic ps -a blows up on python3

### PR DESCRIPTION
**Pull request by rhatdan**
Not sure why you need to change encoding, this is causing issues
on atomic with python3.

### CODE REVIEW

**Comment by rhatdan** [comment]
@giuseppe PTAL

**Comment by rhatdan** [comment]
@jlebon We need ython-docker-py, python3-docker-py, python-slip-dbus and python3-slip-dbus installed in jenkins for these tests to pass.
@jwhonce ^^

**Comment by jlebon** [comment]
bot, retest this please

**Comment by jlebon** [comment]
bot, retest this please

**Comment by jlebon** [comment]
bot, retest this please

**Comment by giuseppe** [comment]
I tested and it works fine for me on Python2 as well so:

@rh-atomic-bot r+ 438d8fa

**Pull request closed without merging**
