### PR TITLE
Refactor to use util.write_* functions

### PR DESCRIPTION
**Pull request by jwhonce**
Normalize encoding of output to stdout and stderr

Signed-off-by: Jhon Honce <jhonce@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@jwhonce You have some test failures. Have to remove "import sys"

**Comment by jwhonce** [comment]
retest this please

**Comment by jwhonce** [comment]
retest this please

**Comment by cgwalters** [comment]
bot, retest this please and also bring me a coffee

**Comment by jwhonce** [comment]
retest this please

**Comment by jlebon** [comment]
Heh, unfortunately it has to be an exact string match. It supports regex though that was broken in previous versions. Though I think that's all cleared up by now, so I'll look into re-enabling it.

**Comment by jlebon** [comment]
bot, retest this please

**Comment by jlebon** [comment]
Seems like the internal infrastructure is still wonky unfortunately. Will keep an eye on it.

**Comment by jwhonce** [comment]
@jlebon Thanks

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request merged**
