### PR TITLE
[merged] Hide system containers feature when OSTree is not installed

### PR DESCRIPTION
**Pull request by giuseppe**

### CODE REVIEW

**Comment by runcom** [comment]
:+1: LGTM

**Comment by rhatdan** [comment]
Can you add something to man page to explain that --system and --set requires the ostree package be installed.

**Comment by giuseppe** [comment]
updated the man pages as well :arrow_up:

**Comment by runcom** [comment]
Do we need another tag to include this? 1.10.2?

**Comment by rhatdan** [comment]
Yes, although are there other issues.

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Comment by runcom** [comment]
Which one? Can we just wait until we sort them all

**Comment by runcom** [comment]
I mean wait to tag a new release

**Comment by rhatdan** [comment]
That is what I had in mind.

**Pull request closed without merging**
