### PR TITLE
Introduce 'atomic diff'

### PR DESCRIPTION
**Pull request by baude**
Allow users to diff between two docker images|container. There
    are two types of diffs that can be run -- a file diff or an
    RPM diff.  The file diff is always the default.  The RPM diff
    can be added with -r.  The file diff can be excluded with -n.

### CODE REVIEW

**Comment by baude** [comment]
Updated to work with python3

**Comment by rhatdan** [comment]
Any chance we can move most of this functionality to a separate diff.py file?  
You should not be doing any output if the user specified --json.  This screws up  any tool
that wants to analyze just the json output.

**Comment by baude** [comment]
@rhatdan renamed subfunctions.py to diff.py ... and moved most all of the diff definition in atomic.py into the diff.py

**Comment by rhatdan** [comment]
Man pages 
bash completion.

**Comment by baude** [comment]
I reworked things per your feedback comments.  The man pages and bash completions were present in the PR already. Is there something wrong with them?

**Comment by rhatdan** [comment]
LGTM

**Comment by cgwalters** [comment]
Worth noting that rpm-ostree carries similar code, although in C.

This introduces a new dependency on `rpm-python` as both a BR and Requires.

**Comment by cgwalters** [comment]
Pushed: http://pkgs.fedoraproject.org/cgit/atomic.git/commit/?id=75d27ff49b897c4e937a0946ab9b379e5b9aae20

**Comment by rhatdan** [comment]
We can't seem to get pylint to pass.  :^(
```
make PYTHON=/usr/bin/python3 install
/usr/bin/python3 setup.py build
running build
running build_py
running build_scripts
/usr/bin/pylint --disable member -E --additional-builtins=_ *.py atomic Atomic tests/unit/*.py
No config file found, using default configuration
************* Module Atomic.diff
E:162,19: Instance of 'TransactionSet' has no 'dbMatch' member (no-member)
```

I think pylint has a bug.

**Comment by cgwalters** [comment]
pylint doesn't understand C modules AFAIK.  Use ` # pylint: disable=no-member` ?

**Comment by rhatdan** [comment]
Thanks that fixed it.

**Comment by rhatdan** [comment]
Running with python3 I see.
```
# docker run -ti --name dan fedora yum -y update
# atomic diff fedora dan
Traceback (most recent call last):
  File "/usr/bin/atomic", line 484, in <module>
    sys.exit(args.func())
  File "/usr/lib/python3.5/site-packages/Atomic/atomic.py", line 1067, in diff
    image_list = helpers.create_image_list(images)
  File "/usr/lib/python3.5/site-packages/Atomic/diff.py", line 61, in create_image_list
    image_list.append(DiffObj(image))
  File "/usr/lib/python3.5/site-packages/Atomic/diff.py", line 109, in __init__
    self.root_path = self.dm.mount(self.name)
  File "/usr/lib/python3.5/site-packages/Atomic/mount.py", line 303, in mount
    driver_mount_fn(identifier, options)
  File "/usr/lib/python3.5/site-packages/Atomic/mount.py", line 394, in _mount_devicemapper
    raise de
  File "/usr/lib/python3.5/site-packages/Atomic/mount.py", line 389, in _mount_devicemapper
    optstring=(','.join(options)))
  File "/usr/lib/python3.5/site-packages/Atomic/mount.py", line 143, in mount_path
    r.stderr.decode(sys.getdefaultencoding()))
Atomic.mount.MountError: Could not mount docker container:
mount -o ro,nosuid,nodev,context="system_u:object_r:svirt_sandbox_file_t:s0:c246,c454" /dev/mapper/docker-8:2-3015133-75a0a9698e44de2960ca1762bd1f1c747e4ba0d9b5ce1369cd76d75c3d7a5c52 /tmp/75a0a9698e44de2960ca
mount: wrong fs type, bad option, bad superblock on /dev/mapper/docker-8:2-3015133-75a0a9698e44de2960ca1762bd1f1c747e4ba0d9b5ce1369cd76d75c3d7a5c52,
       missing codepage or helper program, or other error

       In some cases useful info is found in syslog - try
       dmesg | tail or so.
```

**Pull request merged**
