### PR TITLE
[merged] atomic: More completely handle failure to import OSTree

### PR DESCRIPTION
**Pull request by cgwalters**
GI raises `ValueError` apparently, not `ImportError`.  So rework
things to be nested and handle the cases of:

 - No GI
 - GI but no OSTree
 - OSTree

### CODE REVIEW

**Comment by lsm5** [comment]
seems to get rid of the `ValueError: OSTree` not found error for me

**Comment by giuseppe** [comment]
thanks for looking into this and fix my old version.  It looks fine and I've done some extra testing.

@rh-atomic-bot r+ fdbe345

**Comment by rhatdan** [comment]
Is this something we need to get into 7.2.5?

**Comment by giuseppe** [comment]
this doesn't affect Atomic Host

**Comment by rhatdan** [comment]
Right but is it something we see blowing up in RHEL when users run atomic CLI?

**Comment by giuseppe** [comment]
correct, this will cause an error as soon as we import Atomic.atomic

**Comment by rhatdan** [comment]
Ok I will push v1.10.3

**Pull request closed without merging**
