### PR TITLE
[merged] Add image container version to json output

### PR DESCRIPTION
**Pull request by giuseppe**
enhance the `ps --json` and `images list --json` output with the image id.

It allows to check what version of an image a container is using, and what is the latest version available (locally) of the image.

A couple of bug fixes are included as well.

@cgwalters

### CODE REVIEW

**Comment by rhatdan** [comment]
Why is it referred to as ImageID in one place and Version in the other?

**Comment by giuseppe** [comment]
I named it Version as there is already an ID in the output and I thought it was clearer to name it Version.  I can rename it if having both Id and ImageID makes no confusion

**Comment by rhatdan** [comment]
Would probably be better to separate out a couple of these pull requests.

**Comment by rhatdan** [comment]
I just think they should be consistent between images and ps command.

**Comment by giuseppe** [comment]
I have updated it to have the same name "image_id" both for `images list --json` and `ps --json`

**Comment by cgwalters** [comment]
@rh-atomic-bot r+ 643e50f

**Pull request closed without merging**
