### PR TITLE
redhat-ci.yml: enable destructive tests

### PR DESCRIPTION
**Pull request by jlebon**
Closes: #808

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by cgwalters** [comment]
Looks like it's missing a `-` for the list.

**Comment by jlebon** [comment]
Hmmm, it's a bit tricky to untangle here.

Some of the unit tests have been failing even from before turning on `ENABLE_DESTRUCTIVE`. @aweiteka can you take a look at the `centos/7/atomic` failure above? It seems like it started failing once https://github.com/projectatomic/atomic/pull/816 got merged.

`ENABLE_DESTRUCTIVE` did make the storage test run, and indeed it seems to be failing. @mvollmer could you take a look?

**Comment by jlebon** [comment]
Once these issues are fixed, let's finally switch homu to gate on the new testers.

**Comment by mvollmer** [comment]
> ENABLE_DESTRUCTIVE did make the storage test run, and indeed it seems to be failing. @mvollmer could you take a look?

The failure is this:

```
++ atomic --debug storage modify --add-device /dev/loop0
+ OUTPUT=''\''Namespace'\'' object has no attribute '\''graph'\''
Traceback (most recent call last):
  File "/usr/bin/atomic", line 185, in <module>
    _class.set_args(args)
  File "/usr/lib/python2.7/site-packages/Atomic/storage.py", line 123, in set_args
    if self.args.graph:
AttributeError: '\''Namespace'\'' object has no attribute '\''graph'\'''
```

Looks like #807 wasn't good enough.  I'll make a better fix.

**Comment by mvollmer** [comment]
@jlebon, once test_storage.sh gets further, we might run into https://github.com/projectatomic/docker-storage-setup/pull/138.  Should we change test_storage.sh to use a real device?

**Comment by mvollmer** [comment]
> Looks like #807 wasn't good enough. I'll make a better fix.

#835

**Comment by rhatdan** [comment]
Yes if we can.

**Comment by jlebon** [comment]
I can make redhat-ci support this, but there's some work to do before that can happen (see https://github.com/jlebon/redhat-ci/issues/22). How reasonable would it be to just use loopback devices in the meantime?

**Comment by jlebon** [comment]
Also, seems like the other PR went in, so let's retry here.
bot, retest this please

**Comment by jlebon** [comment]
bot, retest this please

**Comment by mvollmer** [comment]
> How reasonable would it be to just use loopback devices in the meantime?

It wont work.  I can try to use iscsi instead of loopback, what about that?

**Comment by mvollmer** [comment]
> It wont work. 

```
INFO: Waiting for device /dev/loop01 to be available. Wait time remaining is 60 seconds
INFO: Waiting for device /dev/loop01 to be available. Wait time remaining is 55 seconds
INFO: Waiting for device /dev/loop01 to be available. Wait time remaining is 50 seconds
INFO: Waiting for device /dev/loop01 to be available. Wait time remaining is 45 seconds
INFO: Waiting for device /dev/loop01 to be available. Wait time remaining is 40 seconds
INFO: Waiting for device /dev/loop01 to be available. Wait time remaining is 35 seconds
INFO: Waiting for device /dev/loop01 to be available. Wait time remaining is 30 seconds
INFO: Waiting for device /dev/loop01 to be available. Wait time remaining is 25 seconds
INFO: Waiting for device /dev/loop01 to be available. Wait time remaining is 20 seconds
INFO: Waiting for device /dev/loop01 to be available. Wait time remaining is 15 seconds
INFO: Waiting for device /dev/loop01 to be available. Wait time remaining is 10 seconds
INFO: Waiting for device /dev/loop01 to be available. Wait time remaining is 5 seconds
INFO: Timed out waiting for device /dev/loop01
ERROR: Partition device /dev/loop01 is not available
```

Note how `docker-storage-setup` mis-predicts the block device name as `loop01`.  I think that's a bug worth fixing, no matter how you look at it.  If you don't want people to use loopback devices, detect them specifically, don't rely on docker-storage-setup being buggy enough to fail with them.

**Comment by jlebon** [comment]
> It wont work

Is this because https://github.com/projectatomic/docker-storage-setup/pull/138 is required for it to work, or because even if it were merged, it wouldn't work?

**Comment by mvollmer** [comment]
>> It wont work

> Is this because projectatomic/docker-storage-setup#138 is required for it to work, [...]

This.  It should work with #138.

**Comment by jlebon** [comment]
This is supported now. Test machines will now have a secondary disk attached. ⬆️

**Comment by mvollmer** [comment]
> This is supported now. Test machines will now have a secondary disk attached. 

Nice, how can I access it?  Is it always `/dev/sda`, for example, or can I get the name from a environment variable?

**Comment by jlebon** [comment]
> Nice, how can I access it?

It will always be `/dev/vdb` AFAICT.

Maybe we should merge this one in so that we can fix the storage issues in another PR.

**Comment by rhatdan** [comment]
@jlebon Do we need an update or should we just merge and fix the issues later?

**Comment by jlebon** [comment]
@rhatdan Let's just merge it in and fix issues in other PRs,

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Comment by jlebon** [comment]
@rh-atomic-bot r+ e879901

**Pull request closed without merging**
