### PR TITLE
Dockertar sha256 helper enhancements

### PR DESCRIPTION
**Pull request by ashcrow**
## Description

- Error when the wrong number of arguments are provided
- Ensure closing of all open items using ``defer``.

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by ashcrow** [comment]
bot retest this please

**Comment by ashcrow** [comment]
Hrm, deferring the close seems to change the result. Looking at it...

**Comment by ashcrow** [comment]
As it turns out the sha instance must be explicitly closed before the sum executes else the results are different.

**Comment by ashcrow** [comment]
bot retest this please

**Comment by ashcrow** [comment]
```
Running test_storage.sh....                     FAIL
```

**Comment by ashcrow** [comment]
CentOS error is unrelated. Will ask for one more retest.

```
wipefs: error: /dev/vdb: probing initialization failed: Device or resource busy
```

**Comment by ashcrow** [comment]
bot, retest this please

**Comment by ashcrow** [comment]
```
+ dnf install -y git make python2-pylint python3-pylint python3-slip-dbus python-gobject-base python-dbus pylint python-slip-dbus python-docker-py python2-dateutil PyYAML rpm-python 'dnf-command(builddep)'
Error: Failed to synchronize cache for repo 'updates'
+ '[' -z ']'
+ make pylint-check
/code/.papr.sh: line 76: make: command not found
```

**Comment by ashcrow** [comment]
@jlebon FYI 🔼

**Comment by giuseppe** [comment]
@rh-atomic-bot r+ 3d1995b

**Comment by jlebon** [comment]
> Error: Failed to synchronize cache for repo 'updates'

That's just flaky infra. :(
See also https://github.com/projectatomic/papr/issues/53.

**Pull request closed without merging**
