### PR TITLE
[merged] Lots of cleanups for pylint and python3-lint warnings

### PR DESCRIPTION
**Pull request by rhatdan**

### CODE REVIEW

**Comment by rhatdan** [comment]
@jlebon Is this an issue with jenkins?

**Comment by jlebon** [comment]
@rhatdan Pylint found some errors:

```
************* Module atomic
...
E:629, 8: Instance of 'Atomic' has no 'systemctl_command' member (no-member)
```

and

```
************* Module test_mount
E: 14, 0: Bad option value 'deprecated-method' (bad-option-value)
E: 15, 0: Bad option value 'deprecated-method' (bad-option-value)
```

**Comment by rhatdan** [comment]
@jlebon I am running my tests locally and they are working, but when I run them here I am seeing

```
/usr/lib/python2.7/site-packages/astroid/brain/brain_gi.py:136: PyGIWarning: OSTree was imported without specifying a version first. Use gi.require_version('OSTree', '1.0') before import to ensure that the right version gets loaded.
  __import__(m)
```

**Comment by jlebon** [comment]
@rhatdan I submitted a PR to your branch to fix the remaining issues.

https://github.com/rhatdan/atomic/pull/3

> I am seeing
>> /usr/lib/python2.7/site-packages/astroid/brain/brain_gi.py:136: PyGIWarning: OSTree was imported without specifying a version first. Use gi.require_version('OSTree', '1.0') before import to ensure that the right version gets loaded.
  __import__(m)

I think that's just whatever lib pylint uses for introspection not knowing that it should require a version first (not that I blame it).

**Comment by jlebon** [comment]
To clarify, I observed the same warnings and errors as the tester locally, though they went away after I upgraded pylint. Though then other issues cropped, which are fixed in rhatdan#3.

**Comment by jlebon** [comment]
Had to do some hackery with pylint on the tester to make v2 and v3 coexist, but hopefully should all be resolved now.

**Comment by jlebon** [comment]
Had a quick review of the full diff, LGTM, 
@rh-atomic-bot r+ 5ad3c76

**Pull request closed without merging**
