### PR TITLE
(DONTMERGE) Allow developers to specify atomic.type label in container image

### PR DESCRIPTION
**Pull request by rhatdan**
If the atomic command sees this flag set then it will automatically install
based on the system type.

### CODE REVIEW

**Comment by rhatdan** [comment]
I have not been able to test, but @giuseppe and @baude PTAL.

I think this should work if user specifies 
```
atomic install --system=False etcd
```
Then even if the etcd container has a label atomic.type="system", it will not install a system container.

**Comment by giuseppe** [comment]
what if we use this new label at `pull` time so to choose the correct storage?

we can then change `install`to check for a system image if there is no docker image with that name, --system will force it to skip the check and directly install the system container.

If an install needs to pull the image first, as there is no docker or system image stored, then we can check for what storage was used by pull before installing it.

**Comment by rhatdan** [comment]
So you want atomic.storage label, where storage could be `docker, ostree,  or container`?

**Comment by rhatdan** [comment]
I have partially done what you want.   But just because the container is stored in ostree, does that indicate that it is a `--system` container?

**Comment by giuseppe** [comment]
@rhatdan, right that could be a problem in future.  Right now, `--storage ostree` means that the container is a system container (or user when using it as not root user).

Should we still keep the label `atomic.type` and infer the storage from that instead of the other way around?  `atomic.type=docker` -> `storage=docker`, `atomic.type=system` -> `storage=ostree`

**Comment by rhatdan** [comment]
@giuseppe we are having a meeting at 1:00 EST to discuss storage for CRI-O I just invited you to it.

**Comment by rhatdan** [comment]
This is handled by other pull requests.

**Pull request closed without merging**
