### PR TITLE
syscontainers: allow to override the OCI runtime

### PR DESCRIPTION
**Pull request by giuseppe**
Allow to override the OCI runtime binary used with an environment variable

### CODE REVIEW

**Comment by rhatdan** [comment]
Should this be an option rather then an env variable?

**Comment by giuseppe** [comment]
bot, please retry

**Comment by giuseppe** [comment]
Yes, I was unsure about it and if it had to have the same visibility as other options.

I've modified the PR and added `--runtime` as an option instead of an environment variable.  It can also be configured from `atomic.conf`

**Comment by TomSweeneyRedHat** [comment]
LGTM, I like the added flexibility with the option.

**Comment by giuseppe** [comment]
@TomSweeneyRedHat  if you are fine with this PR, please use `@rh-atomic-bot r+ <SHA1 CHECKSUM>` so that it can be merged

**Comment by giuseppe** [comment]
@rh-atomic-bot r- 916aa7e

**Comment by TomSweeneyRedHat** [comment]
@rh-atomic-bot  r+ 916aa7e

**Comment by TomSweeneyRedHat** [comment]
@giuseppe  I'm not sure I'm authorized for that, but we'll see.

**Comment by TomSweeneyRedHat** [comment]
Just bounced me back.  @rhatdan should be on-line early tomorrow.

**Comment by giuseppe** [comment]
@TomSweeneyRedHat I will merge adding you as approver:

@rh-atomic-bot r=TomSweeneyRedHat 6839456 

Thanks for the review!

**Comment by giuseppe** [comment]
@rh-atomic-bot r=TomSweeneyRedHat 916aa7e

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Comment by giuseppe** [comment]
@rh-atomic-bot r=TomSweeneyRedHat 916aa7e

**Comment by giuseppe** [comment]
@rh-atomic-bot retry

**Pull request closed without merging**
