### PR TITLE
Add noprune to image deletion

### PR DESCRIPTION
**Pull request by baude**
Correcting a bug observed by the openscap team where under
    certain conditions, the deletion of a temporary image would
    cause a traceback when noprune=False.

    Added a loop with timeout for unmounting by path to prevent
    race failures between openscap, docker, the filesystem, and/or
    dms.

### CODE REVIEW

**Comment by ybznek** [comment]
@baude Thanks, it fixes random issues which we have in oscapd https://github.com/OpenSCAP/openscap-daemon/issues/34

**Comment by cgwalters** [comment]
Commit message is indented again.

**Comment by baude** [comment]
Lazy cannot be used because the next call will be to delete the CM device.  So all we would be doing is pushing the issue to dmsetup.  It needs to be done here unless someone else has a better idea.

Fixed indents.

**Comment by cgwalters** [comment]
Can't we use `dmsetup remove --deferred` then?

**Comment by rhatdan** [comment]
@rhvgoyal PTAL

**Comment by cgwalters** [comment]
I'm not strongly objecting to this patch, but I'd at least like to be sure we've tried to not poll.  Polling costs power, increases latency etc.

**Comment by rhvgoyal** [comment]
I agree. That we can use lazy unmount followed by deferred device removal. But the question I have is that why mount point is buy and device is busy? Can that be added as part of commit message.

**Comment by baude** [comment]
The fact is that we dont entirely know.  We suspect that either it is a race condition of some sort (typically lsof doesnt show any open files) or there is some leftover openscap process still wrapping up. Members of the openscap team have suggested as such.

So bottom line, while we have been unable to pin it down, i'd rather not have the scan fail and oscapd crash.

If folks are ok with lazy and deferred, i'll code it up as such.  I will say the proposed patch has been tested and works.

**Comment by cgwalters** [comment]
It looks like deferred remove on the docker side requires adding:

```
--storage-opt dm.use_deferred_removal=true
```

to the daemon options.  Can you test that?

**Comment by cgwalters** [comment]
@rhvgoyal in https://github.com/docker/docker/commit/51e059e7e90f37848596a0b6ec83f7835e6e4131 you say "By default feature will be turned off."  But why is that?

**Comment by rhvgoyal** [comment]
@cgwalters Just being safe. It was such a new feature and there has been push back from lvm team about the idea of deferred remove and deferred delete in production. So I did not make these new features as docker deafault. Instead made them fedora/rhel defaults by modifying docker-storage-setup and passing them as options to docker daemon.

**Comment by rhvgoyal** [comment]
@cgwalters I think problem @baude is facing not because of docker but because atomic is trying to unmount and remove a device. I suspect that this device is somehow used by docker an that's why it fails. Not sure though in what cases it is used by docker.

**Comment by baude** [comment]
I believe this is up to everyones specs.  I added a route through for lazy/deferred when it detects if the options are set in dockerd.

**Comment by rhatdan** [comment]
@rhvgoyal @cgwalters PTAL

**Comment by baude** [comment]
Reworked per @cgwalters  comments

**Comment by jlebon** [comment]
Seems like one of the unit tests is failing. Could you look into that?

```
UNIT TESTS:
...F.......
======================================================================
FAIL: test_mount_excepts_unknown_backend (test_mount.TestAtomicMount)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jenkins/workspace/atomic-upstream-test/atomic/tests/unit/test_mount.py", line 14, in test_mount_excepts_unknown_backend
    self.assertRaisesRegexp(mount.MountError, exp, m.mount, 'fedora:22')
AssertionError: "Atomic mount is not supported on the foobardriver docker storage backend." does not match "fedora:22 did not match any image or container."
```

Let me know if you're not able to reproduce this locally.

**Comment by jlebon** [comment]
Thanks @baude for fixing the test. :+1:

**Comment by baude** [comment]
@rhatdan Ok reworked per our conversation yesterday and it passes the tests.

**Comment by baude** [comment]
Adding message as @rhatdan recommends.

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
