### PR TITLE
syscontainers: print an user friendly message if a layer is missing

### PR DESCRIPTION
**Pull request by giuseppe**
If for any reason a layer is missing, print a nicer message instead of
crashing.

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
Is there any way for the tool to attempt to pull the image again?

**Comment by giuseppe** [comment]
Good idea.  I've added a patch to automatically retry a pull if the image is missing any layer when checked out.

**Comment by giuseppe** [comment]
tests are passing \o/

**Comment by giuseppe** [comment]
@rhatdan fine to merge this?

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
