### PR TITLE
Proxy new `rpm-ostree deploy` command

### PR DESCRIPTION
**Pull request by mbarnes**
I just added a new `deploy` command to `rpm-ostree` in https://github.com/projectatomic/rpm-ostree/pull/178.

Here's the changes necessary to proxy it through `atomic host`.

### CODE REVIEW

**Comment by mbarnes** [comment]
Man page updated.

I noticed the options section isn't quite right since different subcommands have different options, but wasn't sure how much you care since we don't ship man pages on Atomic.

**Comment by rhatdan** [comment]
We ship the man pages inside of the *-tools containers, RHEL-tools for example.

We should fix the man pages but that should not block this request.

**Comment by mbarnes** [comment]
Fixed the bash completion for the `deploy` command.  This can be squashed with the first commit.

I also went through the other `atomic host` commands and updated their bash completion.

**Comment by rhatdan** [comment]
LGTM squash the commits, and I will merge.

**Comment by mbarnes** [comment]
Squashed.

**Pull request merged**
