### PR TITLE
Wip - DO NOT MERGE

### PR DESCRIPTION
**Pull request by baude**
## Related Bugzillas
-
-

## Related Issue Numbers
-
-

## Pull Request Checklist:

If your Pull request contains new features or functions, tests are required. If the PR is a bug fix and no tests exist, please consider adding some to prevent regressions.
- [ ] Unittests
- [ ] Integration Tests

### CODE REVIEW

**Comment by baude** [comment]
bot, retest this please

**Comment by jlebon** [comment]
There's no `.papr.yml` file so there's nothing to test. :)

To cherry-pick my commit from the other PR, you should be able to do (assuming you're on your `wip` branch):

```
git reset --hard origin/master
git fetch origin pull/1056/head
git cherry-pick FETCH_HEAD
... hack as usual ...
```

**Comment by baude** [comment]
@giuseppe @yuqi-zhang can you guys peek at the system_containers related failures? ill look at the others.

**Comment by baude** [comment]
@giuseppe @yuqi-zhang also not that in in the case of some of the system_containers tests, they fail differently on atomic vs cloud

**Comment by giuseppe** [comment]
the error I am seeing:
```
Traceback (most recent call last):
  File "/usr/bin/atomic", line 185, in <module>
    sys.exit(_func())
  File "/usr/lib/python3.6/site-packages/Atomic/containers.py", line 136, in ps_tty
    container_objects = self._ps()
  File "/usr/lib/python3.6/site-packages/Atomic/containers.py", line 206, in _ps
    containers = self.filter_container_objects(self.beu.get_containers())
  File "/usr/lib/python3.6/site-packages/Atomic/containers.py", line 123, in filter_container_objects
    filtered_objs = copy.deepcopy(con_objs)
```

should be fixed on master.  Could you try to rebase this PR on top of master?

**Pull request closed without merging**
