### PR TITLE
[merged] Fix build issues on python3 with python3-pylint

### PR DESCRIPTION
**Pull request by rhatdan**
Force make test to test python3-pylint.

Our tests are not catching python3 issues.  This patch fixes some issues and forces python3-pylint to to be tested.

### CODE REVIEW

**Comment by jlebon** [comment]
bot, retest this please

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Comment by rhatdan** [comment]
@rh-atomic-bot retest

**Comment by jlebon** [comment]
I think homu was down earlier, so it didn't catch your r+.
@rh-atomic-bot r+

**Pull request closed without merging**
