### PR TITLE
[merged] backends: has image|container return objects

### PR DESCRIPTION
**Pull request by baude**
If the has_image|has_container evals to True, then return
the proper object; else None

### CODE REVIEW

**Comment by baude** [comment]
@giuseppe Is this what you had in mind? I want to defer the renaming of has_image|has_container due to conflict with existing code.

**Comment by giuseppe** [comment]
@rh-atomic-bot r+ f8d570c

**Comment by baude** [comment]
@rh-atomic-bot retest

**Comment by baude** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
