### PR TITLE
help: add -t argument to groff call to preprocess tables

### PR DESCRIPTION
**Pull request by pkubatrh**
## Description
This PR adds the `-t` argument to `groff` invocation via `atomic help`. This is done so that `atomic help` is able to properly print out help files that are using `tbl(1)` descriptions of tables.

## Related Issue Numbers
https://github.com/sclorg/postgresql-container/issues/174 by @TomasTomecek 

## Pull Request Checklist:

If your Pull request contains new features or functions, tests are required. If the PR is a bug fix and no tests exist, please consider adding some to prevent regressions.
- [ ] Unittests
- [x] Integration Tests

### CODE REVIEW

**Comment by TomasTomecek** [comment]
Awesome!

Would you mind adding a simple table here https://github.com/projectatomic/atomic/blob/master/tests/test-images/help.1 and adding a test case here? https://github.com/projectatomic/atomic/blob/master/tests/integration/test_help.sh

**Comment by pkubatrh** [comment]
Test case has been added.
The test case checks for the presence of a `tbl(1)` description that should not be present in the output if the help file got preprocessed properly.

**Comment by TomasTomecek** [comment]
Awesome, great work!

LGTM

```
Running test_help.sh....                        PASS
```

**Comment by rhatdan** [comment]
bot, add author to whitelist

**Comment by rhatdan** [comment]
@rh-atomic-bot r+ 466cb22

**Comment by TomasTomecek** [comment]
I don't understand the CI failure, these are the last lines from the test run:

```
+ atomic --debug images list -f type=ostree
+ assert_matches atomic-test-system /var/tmp/checkout/.tmp.8fXPTFQAe2/images.out
+ grep -q -e atomic-test-system /var/tmp/checkout/.tmp.8fXPTFQAe2/images.out
+ atomic images list -f repo=atomic-test-system --json
+ python -c 'import json; import sys; sizes = [str(i["virtual_size"]) for i in json.load(sys.stdin)]; sys.exit(len([x for x in sizes if x != sizes[0]]))'
+ teardown
+ set +o pipefail
+ atomic --debug -y containers delete busybox
+ true
+ ostree --repo=/var/tmp/checkout/.tmp.8fXPTFQAe2/repo refs --delete ociimage
```

To me it's not obvious what went wrong. Since the test failure is in `test_system_containers_images.sh`, @giuseppe would you be able to help us out here?

**Comment by giuseppe** [comment]
@TomasTomecek yes, I am debugging this issue right now.  I also encountered it, something must be changed in the tests environment

**Comment by giuseppe** [comment]
@pkubatrh can you rebase and push -f this PR?  The tests failures should be fixed now on master

**Comment by pkubatrh** [comment]
Rebased against master

**Comment by giuseppe** [comment]
@rh-atomic-bot r+ e9ee741

**Pull request closed without merging**
