### PR TITLE
Do not build atomic with an egg file

### PR DESCRIPTION
**Pull request by baude**
setup.py: egg files are hard to debug and working with,
        espicially on a platform like Atomic.

### CODE REVIEW

**Comment by rhatdan** [comment]
@baude tests are blowing up with the change?

**Comment by baude** [comment]
@rhatdan I believe this is correct now.  The result is that instead of getting all of the atomic "inside" the egg-file, we now get an egg-file for info but atomic ends up in its own directory in /usr/lib/python2/site-packages/ ... this is handy for doing debugging.

**Comment by rhatdan** [comment]
Arrggg we have gone back and forth on this many times.  On where the version should be stored.

https://github.com/projectatomic/atomic/pull/130

@cgwalters @rtnpro

**Comment by baude** [comment]
Well, the main change is for the egg builds.  The rest of the changes is to deal with the get_distribution call that was being used in __init__.  If you prefer the version, author, author_email, etc to be stored in setup.py I can rework.

**Comment by rhatdan** [comment]
Yes it should stay in setup.py.

**Comment by rhatdan** [comment]
I am merging this, if it is a problem.  @cgwalters and you need to get in a cage match.

**Pull request merged**
