### PR TITLE
Atomic/scan.py SELinux prevents bind mounting

### PR DESCRIPTION
**Pull request by baude**
Discovered a bug that revealed SELinux was preventing a proper
bind mount for /scanout.  Added ':rw,Z' to the docker command
used to launch scanners.

Also, altered the DEBUG bool to more appropriately use the
atomic --debug bool.

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM.  Only thing I am a little worried about is docker handing :Z when SELinux is disabled.

**Comment by baude** [comment]
@rhatdan do you want me to conditionally check getenforce and alter the docker call accordingly ?

**Comment by rhatdan** [comment]
I think it should just work. without having to hack it out.  I of course do not have an SELinux disable system to test on.

**Comment by baude** [comment]
@rh-atomic-bot I just tested on a permissive system.  Appears ok.

**Comment by rhatdan** [comment]
@baude Need to update the pull request.

**Pull request merged**
