### PR TITLE
Revert "Fix run to use command and args, to make help message correct"

### PR DESCRIPTION
**Pull request by baude**
This reverts commit aed68da24c0db3ea7e2e3bd4de0904c6b67115e4.

### CODE REVIEW

**Comment by miabbott** [comment]
Worked for me.  👍

**Comment by cgwalters** [comment]
The original commit only *very* tersely explained what it was fixing - presumably something broke - what? And do we care about the help issue?

**Comment by rhatdan** [comment]
@rh-atomic-bot r+ dca434e

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Comment by cgwalters** [comment]
@rh-atomic-bot retry

**Pull request closed without merging**
