### PR TITLE
Atomic/backends/_docker.py: Correct run flow

### PR DESCRIPTION
**Pull request by baude**
## Description
As pointed out in issue #1023, when you run an interactive
container and then subsequently run it with commands, you can
get a case where the container is running.  If you run another
image that will end up using the same container name but is born
of a different image, you get confusion.

In this case, we adopt the --replace function as we did with earlier
run/image mix-ups.

## Related Issue Numbers
- #1023 
-

## Pull Request Checklist:

If your Pull request contains new features or functions, tests are required. If the PR is a bug fix and no tests exist, please consider adding some to prevent regressions.
- [ ] Unittests
- [ ] Integration Tests

### CODE REVIEW

**Comment by baude** [comment]
@miabbott mind trying ?

**Comment by rhatdan** [comment]
Using @miabbott Tests could you demonstrate what happens with this patch?

**Comment by miabbott** [comment]
This fixes the problem reported in #1023 

```
# ./atomic run registry.fedoraproject.org/fedora:25
docker run -t -i --name fedora registry.fedoraproject.org/fedora:25 /usr/bin/bash
[root@bd8f8983d70b /]# grep PRETTY /etc/os-release 
PRETTY_NAME="Fedora 25 (Twenty Five)"
[root@bd8f8983d70b /]# exit
exit

# ./atomic run registry.fedoraproject.org/fedora:25 date
fedora
Tue Jun  6 19:33:12 UTC 2017

# ./atomic run registry.fedoraproject.org/fedora:26 grep PRETTY /etc/os-release
Warning: container 'fedora' already points to registry.fedoraproject.org/fedora:25
Run 'atomic run fedora' to run the existing container.
Run 'atomic run --replace 'registry.fedoraproject.org/fedora:26' to replace it

# ./atomic run registry.fedoraproject.org/fedora:26 date
Warning: container 'fedora' already points to registry.fedoraproject.org/fedora:25
Run 'atomic run fedora' to run the existing container.
Run 'atomic run --replace 'registry.fedoraproject.org/fedora:26' to replace it
```

**Comment by rhatdan** [comment]
LGTM

**Comment by baude** [comment]
@rh-atomic-bot r+  	cb49b5d

**Pull request closed without merging**
