### PR TITLE
Resolve version info from setup.py using pkg_resources.

### PR DESCRIPTION
**Pull request by rtnpro**
This fixes version info resolution during using setup.py with deps installed and version resolution from ``Atomic/__init__.py`` too. This is in response to https://github.com/projectatomic/atomic/issues/112#issuecomment-134492154

### CODE REVIEW

**Comment by rtnpro** [comment]
After these changes, ``python setup.py develop`` and ``python setup.py install`` ran seamlessly and installed all the needed python dependencies from ``requirements.txt``

**Comment by rhatdan** [comment]
LGTM 
@cgwalters PTAL

**Comment by rhatdan** [comment]
@rtnpro Please update pull request.

**Comment by rtnpro** [comment]
@rhatdan, I rebased branch on top of current master and resolved the conflicts :)

**Comment by rhatdan** [comment]
LGTM

**Comment by cgwalters** [comment]
This looks like it introduces a hard runtime dependency on setuptools which is a bit unfortunate - e.g. on Atomic Host it's the only thing pulling in setuptools.

**Comment by rhatdan** [comment]
Ok we don't want that.

**Pull request merged**
