### PR TITLE
[merged] atomic.conf: Set docker as default backend

### PR DESCRIPTION
**Pull request by baude**
Setting docker as the default backend instead of ostree.

### CODE REVIEW

**Comment by baude** [comment]
@rhatdan please eval and merge

**Comment by rhatdan** [comment]
Can you cleanup the atomic pull man page also.  Looks like it needs fixes.

**Comment by rhatdan** [comment]
Use the --ostree option to store it into the OSTree repository.
should be

       Use the --storage ostree option to store it into the OSTree repository.

**Comment by rhatdan** [comment]
atomic pull [-h|--help] [--storage=[ostree|docker]] IMAGE

**Comment by rhatdan** [comment]
All pull examples should be --storage ostree.  Also needs mention of the conf file.

**Comment by baude** [comment]
Ok and added the -t|--type for atomic registries too.

**Comment by rhatdan** [comment]
I think the systemcontainers tests might break with this changes also.

**Comment by rhatdan** [comment]
We also need to expand some of the man pages to show non ostree pulls.  Perhaps something with trust, breaking.

**Comment by rhatdan** [comment]
Otherwise LGTM.

**Comment by baude** [comment]
updated...

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
