### PR TITLE
atomic_dbus: fix VulnerableInfo method

### PR DESCRIPTION
**Pull request by larskarlitski**
Pull request #771 broke the D-Bus API.

### CODE REVIEW

**Comment by rhatdan** [comment]
@baude PTAL

**Comment by stefwalter** [comment]
The regression that this pull request fixes sadly was delivered and affects users of Fedora 25 and Fedora 24: https://bugzilla.redhat.com/show_bug.cgi?id=1414010

**Comment by baude** [comment]
@rh-atomic-bot retest

**Comment by baude** [comment]
@rh-atomic-bot r+ 36ffbb8

**Pull request closed without merging**
