### PR TITLE
Add tests for Atomic diff and top

### PR DESCRIPTION
**Pull request by baude**
Basic tests for atomic diff and top which should catch
basic code regressions.

### CODE REVIEW

**Comment by jlebon** [comment]
Thanks, that's a good start!

One good future improvement on this is doing some data validation on the output (e.g. not just checking that `atomic top` quits nicely). Maybe those would belong more in new unit tests, or maybe they could be fit into these ones.

**Comment by jlebon** [comment]
```
+ /usr/bin/coverage run --source=./Atomic/ --branch --append atomic top --quit
Traceback (most recent call last):
  File "atomic", line 501, in <module>
    sys.exit(_func())
  File "/home/jenkins/workspace/atomic-upstream-test/atomic/Atomic/top.py", line 92, in atomic_top
    old_settings = termios.tcgetattr(fd)
error: (25, 'Inappropriate ioctl for device')
```

I'm guessing this is probably due to Jenkins not allocating a TTY.

**Comment by jlebon** [comment]
Hmm, it passed, but it seems like it didn't output anything. Is that expected?

```
                            ATOMIC TOP
                            
[7mCONTA(I)NER* (N)AME     (P)ID      (C)PU  (M)EM  CMD       [0m
```

**Comment by jlebon** [comment]
bot, retest this please

**Comment by baude** [comment]
@rh-atomic-bot  Ready for your review again ....

**Comment by baude** [comment]
@rhatdan Good to go now.  Please consider and merge.  Feedback welcome.

**Comment by jlebon** [comment]
@baude Nice! Would you consider adding a quick grep of the container ID in the `atomic top` output just so something like this doesn't slip by in the future?

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
