### PR TITLE
Atomic now has --user flag.

### PR DESCRIPTION
**Pull request by mtohmaz**
Atomic now has --user flag which creates a BARE_USER repo locally to allow non-privileged user to pull images.

### CODE REVIEW

**Comment by rhatdan** [comment]
I need man page changes, test suite, bash completions...

**Comment by giuseppe** [comment]
I'd move the logic of the new function `_get_local_ostree_repo` into the existing `_get_ostree_repo` as the two differences (path and use `OSTree.RepoMode.BARE_USER`) can be easily managed there.  `_get_ostree_repo` is already used in other places, so I think it is better to check if it is running as user only in one place (`_get_ostree_repo`).

More important: how is an user image going to look like?  The current system images use runc and systemd, while, I assume, we will use bubblewrap for user images.  We will need to store some extra information on how the user image is installed and executed.  Where this information will be?  How installing and executing an user image will look like?

**Comment by rhatdan** [comment]
Yes that is what we need to begin designing.  We need some kind of local configuration to define how to run a bubblewrap container, a possible solution would be to drop a OCI specification and then have a tool to translate OCI Specs to bubblewrap CLI.

**Comment by giuseppe** [comment]
would it reasonable to add OCI specs support to bubblewrap so that the same configuration (and to some extend the same process to install an image) can be used?

**Comment by rhatdan** [comment]
There is real reluctance to add any kind of object processing to a SETUID app.  So it would be preferred that this happens in non priv mode before executing the SETUID app.

**Comment by rhatdan** [comment]
@mtohmaz Man pages? Command Completion?  Tests?

@cgwalters PTAL

**Comment by mtohmaz** [comment]
I'm still working on the tests, but I'll push everything once I finish them this morning.

**Comment by giuseppe** [comment]
I've spent some time during the weekend to write a wrapper around bubblewrap that reads the configuration from an OCI conf file and generates the command line for bubblewrap:

https://github.com/giuseppe/bubblewrap/tree/bwrap-oci

Still it is far from being complete, it lacks many options and it is quite hacky/buggy, but it can be used as a starting point:

```
$ sudo dnf install--releasever 24 --installroot=rootfs emacs
$ ocitools generate --tty --args /usr/bin/emacs > config.json
$ bwrap-oci
# ...emacs running..
```

**Comment by jlebon** [comment]
bot, retest this please

**Comment by rhatdan** [comment]
@mtohmaz Needs a rebase.

**Comment by rhatdan** [comment]
@mtohmaz PTAL

**Comment by jlebon** [comment]
bot, retest this please

**Pull request merged**
