### PR TITLE
Fix tag for docker images

### PR DESCRIPTION
**Pull request by yuqi-zhang**
Decompose the dest name to appease docker api.

Signed-off-by: Yu Qi Zhang <jerzhang@redhat.com>

## Related Issue Numbers
https://github.com/projectatomic/atomic/issues/1000

### CODE REVIEW

**Comment by baude** [comment]
@miabbott can you verify this fixes your issue?

**Comment by miabbott** [comment]
@baude I'll verify it only if @yuqi-zhang makes a unit test for it.  :grinning:

**Comment by baude** [comment]
@yuqi-zhang @miabbott is right, can you make an integration or unit test for this?

**Comment by miabbott** [comment]
This does fix #1000 for me

**Comment by yuqi-zhang** [comment]
Will do

**Comment by giuseppe** [comment]
is https://github.com/projectatomic/atomic/pull/1014 a duplicate of this?

**Comment by yuqi-zhang** [comment]
Yes, closing in favor of #1014

**Pull request closed without merging**
