### PR TITLE
rpm: fix installation with latest dnf

### PR DESCRIPTION
**Pull request by giuseppe**
I've noticed this error while installing a system container using an updated dnf version.

### CODE REVIEW

**Comment by giuseppe** [comment]
Thanks for the quick review!

@rh-atomic-bot r=TomasTomecek

**Comment by jlebon** [comment]
The tester is timing out because the `centos/7/atomic/alpha` image no longer exists. We deleted it a few days ago, but it looks like PAPR isn't handling that change gracefully. Anyway, once https://github.com/projectatomic/atomic/pull/1184 goes in, it should be fine!

**Comment by jlebon** [comment]
@rh-atomic-bot retry

**Comment by jlebon** [comment]
Bahh, I expected the `retry` to cause #1184 to go first. Let's temporarily `r-` this one.
@rh-atomic-bot r-

**Comment by jlebon** [comment]
@rh-atomic-bot retry

**Comment by ashcrow** [comment]
Looks like the flake we've seen often:

```
ERROR: Failed to unmount /var/lib/docker /var/lib/docker/containers /var/lib/docker/overlay2
```

**Comment by ashcrow** [comment]
@rh-atomic-bot retry

**Pull request closed without merging**
