### PR TITLE
Add integrations tests for atomic_dbus_client.py

### PR DESCRIPTION
**Pull request by baude**
We need to make sure the atomic_dbus_client code works and if something
in atomic_dbus.py changes, the client should either be updated or still
work.

### CODE REVIEW

**Comment by jlebon** [comment]
bot, retest this please

**Comment by baude** [comment]
@rhatdan ok this is looking good now

**Comment by rhatdan** [comment]
@rh-atomic-bot r+ daddc59

**Comment by baude** [comment]
@rh-atomic-bot retry

**Comment by baude** [comment]
@rh-atomic-bot retry

**Pull request closed without merging**
