### PR TITLE
[merged] atomic: read default values from manifest file

### PR DESCRIPTION
**Pull request by giuseppe**
Introduce a new "manifest.json" file where it is possible to store
more information related to the system container.

A first need of this file is to store default values when
--set=NAME=VALUE is not provided.

The Hello World example was modified to take advantage of this new feature:

https://github.com/giuseppe/atomic-oci-containers/blob/master/hello-world/manifest.json

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
Where is this file stored? Are you shipping it inside of the container bundle?

**Comment by giuseppe** [comment]
yes, the file is stored under `/exports` as all other files

**Comment by rhatdan** [comment]
Ok I have not read this code, sot this is just atomic command reading into the container image for files under /exports.

**Comment by giuseppe** [comment]
yes, correct, all the logic to handle files under `/exports` is in the atomic command.  Both runc and systemd have no direct access to them

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
