### PR TITLE
smarter_copy(): Split into separate copy() and remove() functions

### PR DESCRIPTION
**Pull request by shishir-a412ed**
Signed-off-by: Shishir Mahajan <shishir.mahajan@redhat.com>

### CODE REVIEW

**Comment by shishir-a412ed** [comment]
In `test_storage.sh` when `teardown()` executes, it calls `smarter_copy()` to copy the backup file (`/etc/sysconfig/docker-storage-setup.atomic-tests-backup`) back to original (`/etc/sysconfig/docker-storage-setup`). However it does not clean it up and leaves the backup file behind.

This PR splits the smarter_copy() into separate copy() and remove() functions which fixes the above issue and easier to read.

ping @rhatdan @baude 

Shishir

**Comment by shishir-a412ed** [comment]
@rhatdan @baude Any updates on this one ?

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
@rh-atomic-bot r+ 740d35f

**Pull request closed without merging**
