### PR TITLE
atomic sign: More fixes, and update for the sigstore layout change

### LINKED ISSUE #929: (atomic sign) does not work at all
1. ```
   Traceback (most recent call last):
     File "./atomic", line 189, in <module>
       sys.exit(_func())
     File "/home/mitr/t/atomic/Atomic/sign.py", line 80, in sign
       manifest = ri.get_manifest()
     File "/home/mitr/t/atomic/Atomic/discovery.py", line 41, in get_manifest
       assert(self.fqdn is not None)
   AssertionError
   ```
   Apparently it is necessary to call `ri.inspect()` before `ri.get_manifest()`; though a clean fix would probably be different, at the very least it would be nice to skip `util.skopeo_inspect` if `self.registry` is specified in the input argument.

1. After adding a `_ = ri.inspect()` in there:
   ```
   $ ATOMIC_CONF=tests/unit/fixtures/atomic.conf ATOMIC_CONFD=/var/empty/ sudo -E ./atomic --debug sign --sign-by=mitr@volny.cz -d . docker.io/library/busybox:latest
   …
   Traceback (most recent call last):
     File "./atomic", line 189, in <module>
       sys.exit(_func())
     File "/home/mitr/t/atomic/Atomic/sign.py", line 85, in sign
       manifest_file.write(manifest)
   TypeError: argument 1 must be string or buffer, not dict
   ```
   It seems `RegistryInspect.get_manifest` should use `return_json=False`, not `True`.

1. Also (after the `_ = ri.inspect()` workaround), only with `--debug`:
   ```
   $ ATOMIC_CONF=tests/unit/fixtures/atomic.conf ATOMIC_CONFD=/var/empty/ sudo -E ./atomic --debug sign --sign-by=mitr@volny.cz -d . busybox:latest
   …
   Traceback (most recent call last):
     File "./atomic", line 189, in <module>
       sys.exit(_func())
     File "/home/mitr/t/atomic/Atomic/sign.py", line 79, in sign
       _ = ri.inspect()
     File "/home/mitr/t/atomic/Atomic/discovery.py", line 34, in inspect
       self.fqdn = self.find_image_on_registry()
     File "/home/mitr/t/atomic/Atomic/discovery.py", line 70, in find_image_on_registry
       util.write_out(i)
     File "/home/mitr/t/atomic/Atomic/util.py", line 189, in write_out
       _output(sys.stdout, output, lf)
     File "/home/mitr/t/atomic/Atomic/util.py", line 202, in _output
       fd.write(output + lf)
   TypeError: unsupported operand type(s) for +: 'dict' and 'str'
   ```

1. After fixing the above:
    ```
    $ ATOMIC_CONF=tests/unit/fixtures/atomic.conf ATOMIC_CONFD=/var/empty/ sudo -E ./atomic --debug sign --sign-by=mitr@volny.cz busybox:latest
   ...
   Traceback (most recent call last):
     File "./atomic", line 189, in <module>
       sys.exit(_func())
     File "/home/mitr/t/atomic/Atomic/sign.py", line 103, in sign
       signature_path = util.get_signature_write_path(reg_info)
     File "/home/mitr/t/atomic/Atomic/util.py", line 671, in get_signature_write_path
       return reg_info.get('sigstore-staging', reg_info.get('sigstore', None))
   AttributeError: 'NoneType' object has no attribute 'get'
   ```
   Unhandled the case when `reg_info = None and default_store = None`

1. Adding an error message in there ends up with:
   ```
   $ ATOMIC_CONF=tests/unit/fixtures/atomic.conf ATOMIC_CONFD=/var/empty/ sudo -E ./atomic --debug sign --sign-by=mitr@volny.cz centos/httpd:latest
   …
   Trying docker.io/centos/httpd:latest...
   No applicable configuration for /centos was found in tests/unit/fixtures/etc/containers/registries.d
   ```
   Apparently `expanded_image_name` ends up as `/centos/httpd:latest`. I don’t immediately see how the `RegistryInspect` class is supposed to work with `.fqdn`, `.registry` etc.

### LINKED ISSUE #931: Update sigstore layout in (atomic sign)
Per https://github.com/containers/image/issues/187 etc., https://github.com/containers/image/pull/247 will change the sigstore layout from `$base/$hostname/$repo-path/$image@$algo:$hex` to `$base/$repo-path/$image@$algo=$hex`. Please update `atomic sign` accordingly.

The replacement of `:` with `=` is simple enough,
```diff
diff --git a/Atomic/sign.py b/Atomic/sign.py
index 57b851f..d41dfef 100644
--- a/Atomic/sign.py
+++ b/Atomic/sign.py
@@ -117,7 +120,7 @@ class Sign(Atomic):
                     if not os.path.exists(signature_path):
                         raise ValueError("The signature path {} does not exist".format(signature_path))
 
-                sigstore_path = "{}/{}@{}".format(signature_path, expanded_image_name.rsplit(':', 1)[0], manifest_hash)
+                sigstore_path = "{}/{}@{}".format(signature_path, expanded_image_name.rsplit(':', 1)[0], manifest_hash.replace(':', '=', 1))
                 self.make_sig_dirs(sigstore_path)
                 sig_name = self.get_sig_name(sigstore_path)
                 fq_sig_path = os.path.join(sigstore_path, sig_name)
```

but I’m not sure what to use instead of `expanded_image` so that the hostname is removed, especially considering that `expanded_image` may be resolved incorrectly (item 5 in #929).

### PR DESCRIPTION
**Pull request by mtrmac**
This
- Modifies the created signature to use a fully explicit docker/distribution reference
- Fixes lookup of `registries.d/*.yaml` configurations if the input was specified without a hostname
- Updates `atomic sign` to use the new sigstore layout (no hostname, and `=` instead of `:`)

Fixes #929 (the remainder)
Fixes #931 

See the individual commit messages for more detailed descriptions.

(Seems to work well enough locally, but I didn’t test this particularly rigorously.)

### CODE REVIEW

**Comment by rhatdan** [comment]
@aweiteka @baude PTAL

LGTM

**Comment by baude** [comment]
Let's give it a spin.

**Comment by baude** [comment]
@rh-atomic-bot r+ 439882a

**Comment by baude** [comment]
@rh-atomic-bot retry

**Comment by baude** [comment]
@rh-atomic-bot retry

**Comment by rhatdan** [comment]
@jlebon Any idea why all tests pass individually then homu fails?

**Comment by jlebon** [comment]
The errors are accessible by clicking on the **status-redhatci** links that the bot posts back.

> dbus.exceptions.DBusException: org.freedesktop.DBus.Python.dbus.exceptions.DBusException: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/00/00f017a8c2a6e1fe2ffd05c281f27d069d2a99323a8cd514dd35f228ba26d2ff/data?Expires=1489506425&Signature=XaisMFWkuI0BdrC-V8P2UK-xnfSpPR6cY8I58ZUybZwl7UfZqZjXyaKMuBi3~g3QoLp8xPCJuGNsNdtIj2jpticx8HDljNOb07MDDMK9uzhT6y0vmvVzYtyWQ2GniKNNjyxTLRVYlS3niskBU1TLil0CZWJf5hGRA-MXdlN-jOc_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: net/http: TLS handshake timeout

> dbus.exceptions.DBusException: org.freedesktop.DBus.Python.dbus.exceptions.DBusException: Command '['/usr/bin/skopeo', '--policy=/etc/containers/policy.json', 'copy', '--remove-signatures', 'docker://docker.io/library/busybox:1.24', 'docker-daemon:docker.io/library/busybox:1.24']' returned non-zero exit status 1

> dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

These all look like infra flakes. They do seem to be having some issues right now: http://status.docker.com/. Though supposedly only Docker Cloud should be affected. It's the downside having tests that rely on things outside their control. :(

@rh-atomic-bot retry

**Comment by baude** [comment]
@rh-atomic-bot retry

**Comment by rhatdan** [comment]
@rh-atomic-bot retry

**Pull request closed without merging**
