### PR TITLE
syscontainers: create the bind source path if it doesn't exist

### PR DESCRIPTION
**Pull request by giuseppe**
and if the user namespace is not used, chown the source bind path to
the current user.

This will allow us to bind only /var/lib/etcd/$NAME.etcd in the etcd
container, instead of /var/lib as it will be created automatically if
it doesn't exist.

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by cgwalters** [comment]
Hum...a lot going on here.  One approach is to require the container to install tmpfiles.d units.  Though then we'd need to track the installation of that file in addition to the systemd unit.  Also thinking...if systemd had `StateDirectory=` (like `RuntimeDirectory=`) that'd be exactly what we want. 

I've been thinking we should actually inject some metadata into the unit file to say that it's a syscontainer - it'd help us track the removal of files we installed.  That was something that always bothered me about the previous `atomic install` - we required users to track files they installed, unlike how rpm/dpkg etc. do it.

**Comment by giuseppe** [comment]
Should the state directory be removed on uninstall?  I think it should not be removed by atomic, unless explicitly specified somehow.

I have used `/var/lib/etcd` for the etcd storage only because it was  already the location used by the etcd rpm and also the Docker etcd container.  Should we instead use something that facilitate the association storage->container, as `/var/lib/atomic/$NAME` or `/var/lib/containers-storage/$NAME`?

**Comment by giuseppe** [comment]
this PR is related: https://github.com/projectatomic/atomic/pull/557

**Comment by giuseppe** [comment]
I had a look at using systemd-tmpfiles to manage these directories, is it fine to assume `systemd-tmpfiles` is used only on `atomic install --user` and `atomic-uninstall` for user containers, while for system containers the conf file can be placed under '/etc/tmpfiles.d'?

Another thing to figure out is how it will work with `update --container`.  We should probably use stop + start the service instead of restart so we have time to cleanup and install the new version of the configuration file.

**Comment by giuseppe** [comment]
I have implemented the system-tmpfiles integration here: https://github.com/projectatomic/atomic/pull/559

**Pull request closed without merging**
