### PR TITLE
--prune is not working with python3 due to encoding

### PR DESCRIPTION
**Pull request by rhatdan**

### CODE REVIEW

**Comment by rhatdan** [comment]
@baude @cgwalters @bexelbie PTAL

**Comment by baude** [comment]
lgtm

**Comment by cgwalters** [comment]
Can we use Linux-kernel (and systemd, and ostree, etc.) style commit messages please?  In this case:

 - Use a prefix header
 - Be imperative

Like:

```
prune: Fix encoding in python3
```

**Comment by rhatdan** [comment]
Fine with me.

**Pull request merged**
