### PR TITLE
Allow users to add ${IMAGE} and ${NAME} to INSTALL/RUN/STOP/UNINSTALL…

### PR DESCRIPTION
**Pull request by rhatdan**
… labels

This will allow users to add random content based off image and container names

### CODE REVIEW

**Comment by stefwalter** [comment]
The regular expression for a basic expansion of variables isn't that hard:

https://github.com/cockpit-project/cockpit/blob/master/pkg/base1/cockpit.js#L2142

**Comment by fche** [comment]
Both a substring-search ${FOO} and simple regex methods suffer from poor quoting-tolerance.  (Imagine a user wants to pass the literal string ${FOO} as an argument, by single-quoting it or \-prefixing at some point.)

**Comment by rhatdan** [comment]
Are either of these comments actually related to the pull request?

**Comment by stefwalter** [comment]
> Are either of these comments actually related to the pull request?

Yes, the variable substitution method is brittle and prone to error.

**Comment by shaded-enmity** [comment]
I think that the simplified way how TeX works can be used to achieve proper substitutions:

```python
class Substitute(object):
       def __init__(self, s = ''):
               self.data = s

       def expand(self):
               return Substitute(self.data.replace(...))

       def __eq__(self, other):
               return self.data == other.data

sub, old = Substitute(""), None
while sub != old:
        old, sub = sub, sub.expand()
```
I.E: keep expanding until both before/after strings are the same

But shouldn't that be a subject for another PR? the original LGTM.

**Comment by rhatdan** [comment]
Lets get the original merged and then we can work on improving it.

**Comment by fche** [comment]
Dan, have you considered making this work by having the atomic driver arrange to put into the environment those two values, and let the INSTALL/RUN/... scripts to find it there (with the same single-quote trick in your 'using-environment-substitution' blog?  So instead of massaging the command strings, automatically pass a standard -e VAR1=value1 -e VAR2=value2 tuple to docker.

**Comment by rhatdan** [comment]
On 05/29/2015 09:32 AM, Frank Ch. Eigler wrote:
>
> Dan, have you considered making this work by having the atomic driver
> arrange to put into the environment those two values, and let the
> INSTALL/RUN/... scripts to find it there (with the same single-quote
> trick in your 'using-environment-substitution' blog? So instead of
> massaging the command strings, automatically pass a standard -e
> VAR1=value1 -e VAR2=value2 tuple to docker.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/projectatomic/atomic/pull/59#issuecomment-106803396>.
>

I guess that would work also.  It would leak the information into the
container, but probably not a bad idea.

**Comment by rhatdan** [comment]
I like @DirectXMan12 fix better.

**Comment by rhatdan** [comment]
https://github.com/projectatomic/atomic/issues/66

**Pull request closed without merging**
