### PR TITLE
Support adding pubkeys from local keyring

### PR DESCRIPTION
**Pull request by aweiteka**
```
$ gpg2 --list-keys
/home/aweiteka/.gnupg/pubring.kbx
---------------------------------
pub   rsa2048 2016-09-29 [SC]
      D2C2475C15A4196CE2C859540EEB7F8664E11092
uid           [ultimate] aweiteka@redhat.com
sub   rsa2048 2016-09-29 [E]
$ sudo GNUPGHOME=~/.gnupg atomic trust add docker.io -k aweiteka@redhat.com
```

### CODE REVIEW

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Comment by cgwalters** [comment]
@rh-atomic-bot r=rhatdan 2da6387

**Comment by cgwalters** [comment]
I'm deploying a new Homu which should make `r+` work again.

**Comment by rhatdan** [comment]
@rh-atomic-bot r=rhatdan 2da6387

**Comment by rhatdan** [comment]
@rh-atomic-bot  retry

**Pull request closed without merging**
