### PR TITLE
make uninstall: remove atomic package

### PR DESCRIPTION
**Pull request by baude**
As a developer, it would be handy to have a make
    uninstall to compliment the use of make install.

    Python has no great way to remove module installs
    when using distutils, hence the use of rm and wildcards
    to remove files.

### CODE REVIEW

**Comment by cgwalters** [comment]
This sort of thing rapidly bitrots.  Which is why robust build/delivery systems use `make install DESTDIR=` and then track the files installed.

You could try e.g. https://www.gnu.org/software/stow/ 
I've been meaning to look at something like that for the `sudo make install` workflow.  (Fun aside; ostree was originally intended to address this use case)

**Comment by baude** [comment]
The DESTDIR is an option.  I'm game if that is preferred.  

It looks like they track the files then by examining the DESTDIR contents.  I saw a reference to
```
# find . -type f -print > ../files.lst
```
being used in example.

What I don't quite see is how things from the DESTDIR to the filesystem.  @cgwalters  do you have an example you can point at?

**Comment by clebergnu** [comment]
Besides that, IMHO, atomic should really try to do a setuptools[1] only install and drop the Makefile install steps. This way it would be possible for developers to do:

```
$ python setup.py develop
```

And use the source tree without *real* installs.

[1] - https://pythonhosted.org/setuptools/setuptools.html#development-mode

**Comment by baude** [comment]
Atomic now uses distutils

**Pull request closed without merging**
