### PR TITLE
Fix pylint errors on re.UNICODE and re.MULTILINE

### PR DESCRIPTION
**Pull request by rhatdan**

### CODE REVIEW

**Comment by rhatdan** [comment]
@baude I can't install your latest patch without this patch,on fedora 26.

**Comment by baude** [comment]
@rhatdan Ill look at this first thing in the AM.  Just using a standard rawhide qcow2 or ?

**Comment by rhatdan** [comment]
Just using my laptop which is running rawhide.  I have  a feeling this is a newer version of pylint, which does not like the constants.  Although the constants seem fine to me.

rpm -q python3-pylint
python3-pylint-1.6.4-2.fc26.noarch

**Comment by baude** [comment]
Im using -1 on F25 with no issues.

**Comment by rhatdan** [comment]
Well lets merge in my patch and it will work on the next version of pylint.

**Comment by rhatdan** [comment]
@baude ANything new on this?

**Pull request closed without merging**
