### PR TITLE
Enable atomic push in dbus and add integrations tests

### PR DESCRIPTION
**Pull request by baude**
For potential cockpit use, we have enabled atomic push.  It returns
a 0 if successful or throws a dbus Exception upon failure.  Added
a series of integrations tests as well.

### CODE REVIEW

**Comment by baude** [comment]
[(5) [Dbus] Add support for atomic push](https://trello.com/c/3SItlEXr/236-5-dbus-add-support-for-atomic-push)

**Comment by rhatdan** [comment]
Should we add a dbus interface to return registry choices for cockpit to display?

**Comment by baude** [comment]
@rhatdan We sure can, but ideally we should be able to detect this on the fly if we can ever get the registry API to just change a bit.   Let me know what you want and I'll do it.

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Comment by rhatdan** [comment]
@rh-atomic-bot r+ b956711

**Pull request closed without merging**
