### PR TITLE
Fixed CLI so that if the user forgets to specify a URL in the config …

### PR DESCRIPTION
**Pull request by jramseye**
…file or via command line, they will be prompted to input one instead of just failing to upload.  Also refactored so code is pep8 compatible

Signed-off-by: jramseye <jramseye@redhat.com>

Fixed bash completion for upload as well.

### CODE REVIEW

**Comment by jramseye** [comment]
This changes it so that, if uploading to pulp, we are also prompted for the URL if not specified.

**Comment by jramseye** [comment]
Removed the extra whitespace

**Comment by rhatdan** [comment]
LGTM

**Comment by jramseye** [comment]
Thanks!

**Pull request merged**
