### PR TITLE
[merged] Return image if exact match

### PR DESCRIPTION
**Pull request by rhatdan**

### CODE REVIEW

**Comment by rhatdan** [comment]
In current code I have three container images named docker
```
atomic mount rhatdan/docker:latest /mnt
"rhatdan/docker:latest" matched multiple items. Try one of the following:
	rhatdan/docker:latest
	dwalsh/docker:latest
	docker.io/docker:latest
```
But even though I use the exact name, it fails.

This patch will fix this issue.

**Comment by rhatdan** [comment]
@baude PTAL

**Comment by baude** [comment]
LGTM

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
