### PR TITLE
docs, pull: add documentation for http: prefix

### PR DESCRIPTION
**Pull request by giuseppe**
Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by giuseppe** [comment]
@miabbott I've checked, and we missed this part in the documentation.  Does this ⬆️ look fine for you?

**Comment by miabbott** [comment]
@giuseppe Could you include an example of using the `http` prefix?

**Comment by giuseppe** [comment]
@miabbott sure.  Just pushed another version that includes the example

**Comment by giuseppe** [comment]
@rh-atomic-bot delegate=miabbott

**Comment by miabbott** [comment]
@rh-atomic-bot r+ 2202d94

**Comment by giuseppe** [comment]
bot, please retry

**Comment by giuseppe** [comment]
I've only rebased it to retrigger the tests:

@rh-atomic-bot r=miabbott 449981f

**Pull request closed without merging**
