### PR TITLE
Run UNINSTALL command even if container name is not same as image

### PR DESCRIPTION
**Pull request by rhatdan**

### CODE REVIEW

**Comment by rhatdan** [comment]
@hhorak could you try out this patch?

Should fix https://github.com/projectatomic/atomic/issues/128

**Comment by rhatdan** [comment]
@hroncok verified this fixed his issue.  Merging.

**Comment by hroncok** [comment]
not sure I ever know about this. did you mean @hhorak?

**Comment by rhatdan** [comment]
Oops sorry.

**Pull request merged**
