### PR TITLE
don't fail when dead images are around

### PR DESCRIPTION
**Pull request by ibotty**
fixes issue #124.

### CODE REVIEW

**Comment by rhatdan** [comment]
@baude @willmtemple Please check this fix?

**Comment by baude** [comment]
@rhatdan  @ibotty I am on vacation but can take a look.  Can either of you remind me how to create a dead container so I can replicate?

**Comment by ibotty** [comment]
I can't replicate them. AFAICT you should be able to get them when nsentering a container and then trying to docker rm it. I never created them on purpose, but sometimes they just emerge and don't go back by itself. Most dead containers (but not all of them) were privileged btw.

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
You can create a dead image by creating one image, then create a container based on the image.  Update the image.  Now rebuild the container.  I think this leaves around a dangling image.

**Pull request merged**
