### PR TITLE
Fix re module bug

### PR DESCRIPTION
**Pull request by aweiteka**

### CODE REVIEW

**Comment by rhatdan** [comment]
Does this fix the problem on RHEL?  Should we have @lsm5 grab this patch for the RHEL7 atomic command?

**Comment by aweiteka** [comment]
> Does this fix the problem on RHEL? Should we have @lsm5 grab this patch for the RHEL7 atomic command?

Yes and yes

**Comment by rhatdan** [comment]
@rh-atomic-bot r=rhatdan fc5536a

**Comment by ddarrah** [comment]
fix is good on RHEL.

**Pull request closed without merging**
