### PR TITLE
atomic: add ability to profile atomic

### PR DESCRIPTION
**Pull request by baude**
Adding a hidden option --profile to allow developers to profile execution
of atomic code. If enabled, a profile report is printed upon completion
of the command for analysis.

### CODE REVIEW

**Comment by rhatdan** [comment]
@rh-atomic-bot r+ f8d56ce

**Comment by jlebon** [comment]
Interesting, somehow when this was r+'ed, it pushed it for testing immediately even though #973 wasn't finished. Weird.

**Comment by cgwalters** [comment]
Let's investigate more if it happens more often.

@rh-atomic-bot retry

**Comment by baude** [comment]
@rh-atomic-bot r+

**Comment by cgwalters** [comment]
@rh-atomic-bot r+ 2a730f7

**Pull request closed without merging**
