### PR TITLE
syscontainers: fix overridable vars

### PR DESCRIPTION
**Pull request by yuqi-zhang**
Allow RUN_DIRECTORY and STATE_DIRECTORY to be overridable if the user
sets them as a value or they are present in manifest.json, as they are
in TEMPLATE_OVERRIDABLE_VARIABLES.

Signed-off-by: Yu Qi Zhang <jerzhang@redhat.com>

### CODE REVIEW

**Comment by yuqi-zhang** [comment]
@giuseppe I'm not sure if we decided to change that behaviour at some point, but if not this should fix it to "--set" -> manifest.json value -> default value priority order.

**Comment by giuseppe** [comment]
@yuqi-zhang yes it looks fine to me, it is probably going to cause a merge conflict in https://github.com/projectatomic/atomic/pull/952 but we will deal with it in the other PR

Thanks for fixing it!

@rh-atomic-bot r+  	b9a7447

**Comment by giuseppe** [comment]
@rh-atomic-bot r+ b9a7447

**Comment by yuqi-zhang** [comment]
Want to give this a shot again @giuseppe

**Comment by giuseppe** [comment]
absolutely!

@rh-atomic-bot r+ b9a7447

**Pull request closed without merging**
