### PR TITLE
Fix typos and update docs to follow --json switch was removed

### PR DESCRIPTION
**Pull request by chuanchang**

### CODE REVIEW

**Comment by chuanchang** [comment]
/usr/bin/pylint -E --additional-builtins=_ *.py atomic Atomic tests/unit/*.py
No config file found, using default configuration
/usr/lib/python2.7/site-packages/astroid/brain/brain_gi.py:136: PyGIWarning: OSTree was imported without specifying a version first. Use gi.require_version('OSTree', '1.0') before import to ensure that the right version gets loaded.
  __import__(m)
************* Module atomic_dbus
E: 88,26: Undefined variable 'import_loc' (undefined-variable)
Makefile:28: recipe for target 'pylint-check' failed
make: *** [pylint-check] Error 2

**Comment by chuanchang** [comment]
The PR 421 fixes Undefined variable 'import_loc' in atomic_dbus.py

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Comment by rhatdan** [comment]
@rh-atomic-bot retest

**Comment by rhatdan** [comment]
@rh-atomic-bot retest

**Pull request merged**
