### PR TITLE
atomic.sh: fix up command forwarding to rhel-tools

### PR DESCRIPTION
**Pull request by jlebon**
Small tweaks to make command forwarding work properly.

### CODE REVIEW

**Comment by bexelbie** [comment]
Should this be modified in the upstream to check for a TOOLSIMG and only call it if defined and default to undefined?  Then in the rhel version add the name?

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
@bexelbie Not sure what you mean, This is defaulted to not execute the atomic command.  If you uncomment the sysconfig line, it will run.

**Comment by jlebon** [comment]
@rhatdan Thanks! I think @bexelbie means that TOOLSIMG shouldn't be defined on Fedora (is that correct @bexelbie?).

**Comment by bexelbie** [comment]
@jlebon yes, that is correct.  Therefore I would expect that this repo wouldn't contain an entry there.  Each distro should modify it before packaging as needed.  However, I may be mistaken.

**Comment by jlebon** [comment]
@bexelbie Agreed. I'll tweak it. (BTW, I looked but it doesn't seem like there's an official equivalent to rhel-tools for Fedora, is there?)

**Pull request merged**
