### PR TITLE
[merged] update default trust policy file

### PR DESCRIPTION
**Pull request by aweiteka**
Installed default policy is https://raw.githubusercontent.com/projectatomic/skopeo/master/default-policy.json Match that file if it doesn't exist.

### CODE REVIEW

**Comment by rhatdan** [comment]
I am not crazy about duplicating this code in two different places, but I don't see an option.  Will 
`atomic trust reset`
Rewrite this file?

**Comment by aweiteka** [comment]
> I am not crazy about duplicating this code in two different places, but I don't see an option.

I agree, although there's no new functionality here. I'm just updating the default and making it a bit cleaner.

> Will atomic trust reset Rewrite this file?

Yes

**Comment by rhatdan** [comment]
@rh-atomic-bot restest

**Comment by rhatdan** [comment]
@rh-atomic-bot test

**Comment by aweiteka** [comment]
@rhatdan should be all set now.

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
