### PR TITLE
Fix atomic storage modify --remove-device issue in list_parents()

### PR DESCRIPTION
**Pull request by shishir-a412ed**
Signed-off-by: Shishir Mahajan <shishir.mahajan@redhat.com>

### CODE REVIEW

**Comment by shishir-a412ed** [comment]
list_parents() should return the parent [:1]. Right now it is returning the children which is causing `test_storage.sh` to fail, when docker is running on lvm thinpool setup.

ping @rhatdan @baude

**Comment by shishir-a412ed** [comment]
So the problem here is: Output of `lsblk -snlp -o NAME /dev/vda1` {The command used to find the parent of a partition} in `list_parents()` function have different output in Fedora (24/25) atomic distributions compared to Fedora rawhide (Non atomic host) distribution.

Output on my Fedora 24 Atomic Host:

````
sh-4.3# lsblk
NAME                            MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sr0                              11:0    1  366K  0 rom  
vda                             252:0    0    6G  0 disk 
├─vda2                          252:2    0  5.7G  0 part 
│ ├─atomicos-docker--pool_tmeta 253:1    0    8M  0 lvm  
│ │ └─atomicos-docker--pool     253:3    0    2G  0 lvm  
│ ├─atomicos-docker--pool_tdata 253:2    0    2G  0 lvm  
│ │ └─atomicos-docker--pool     253:3    0    2G  0 lvm  
│ └─atomicos-root               253:0    0    3G  0 lvm  /sysroot
└─vda1                          252:1    0  300M  0 part /boot
````
Now if I want to find the parent of `/dev/vda1` partition, I would run `lsblk -snlp -o NAME /dev/vda1` and it will output:
````
/dev/vda1 
/dev/vda
````

NOTE: Partition is the first line followed by the parent on the second line.
Hence in `list_parents() {  ..... split lines()[1:] }` would pick the parent `/dev/vda` correctly.

Output on my Fedora Rawhide distribution:

````
sh-4.4# lsblk
NAME                          MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
loop0                           7:0    0  100G  0 loop 
└─docker-253:0-25241738-pool  253:5    0  100G  0 dm   
loop1                           7:1    0    2G  0 loop 
└─docker-253:0-25241738-pool  253:5    0  100G  0 dm   
sr0                            11:0    1 1024M  0 rom  
vda                           252:0    0   50G  0 disk 
├─vda1                        252:1    0    1G  0 part /boot
└─vda2                        252:2    0   49G  0 part 
  ├─fedora-root               253:0    0   15G  0 lvm  /
  ├─fedora-swap               253:1    0  2.1G  0 lvm  [SWAP]
  ├─fedora-docker--pool_tmeta 253:2    0   52M  0 lvm  
  │ └─fedora-docker--pool     253:4    0 12.7G  0 lvm  
  └─fedora-docker--pool_tdata 253:3    0 12.7G  0 lvm  
    └─fedora-docker--pool     253:4    0 12.7G  0 lvm  
vdb                           252:16   0   20G  0 disk 
└─vdb1                        252:17   0   20G  0 part 
````

Now I would run the same command `lsblk -snlp -o NAME /dev/vda1` to find it's parent.

Output:
````
/dev/vda
/dev/vda1
````
Note: Here parent is the first line, followed by the partition. Hence the existing code will fail.
I think relying on the output of lower level commands is shaky premise, but I don't see a way around this particularly in this usecase. 

@rhatdan @baude WDYT ?

Shishir

**Comment by rhatdan** [comment]
test-storage is failing.

**Comment by shishir-a412ed** [comment]
@rhatdan Did you read my comment ? :)
https://github.com/projectatomic/atomic/pull/882#issuecomment-278694901

**Comment by rhatdan** [comment]
Yes, I read it, but you need to fix the tests.

**Comment by shishir-a412ed** [comment]
@rhatdan fixed the tests. PTAL.

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Comment by rhatdan** [comment]
@rh-atomic-bot r=rhatdan d78ccb3

**Pull request closed without merging**
