### PR TITLE
[merged] Added pylint disable no-member to OSTree.RepoCheckoutOptions()

### PR DESCRIPTION
**Pull request by mtohmaz**

### CODE REVIEW

**Comment by cgwalters** [comment]
@rh-atomic-bot r+ 3d46f56

**Comment by cgwalters** [comment]
@rh-atomic-bot retry

**Comment by rhatdan** [comment]
@rh-atomic-bot retry

**Comment by rhatdan** [comment]
@mtohmaz What is the purpose of the separate patch c224782?  You are removing --user from bash completion?

**Comment by cgwalters** [comment]
@rh-atomic-bot r+ ee74e77

**Comment by cgwalters** [comment]
Yeah, @mtohmaz can you split this into separate PRs?

**Comment by mtohmaz** [comment]
Should be all set now, added a description to the commit message to explain what it's for.

**Comment by cgwalters** [comment]
@rh-atomic-bot r+ 4797d9f

**Pull request closed without merging**
