### PR TITLE
[merged] Implement dbus interface for atomic commands

### PR DESCRIPTION
**Pull request by rhatdan**
Most of the changes here are in the restructuring of the atomic_dbus and atomic_client.py files.  
Additional interfaces to both, and a bunch of test scripts to make stress the dbus interface.

### CODE REVIEW

**Comment by rhatdan** [comment]
@baude @aweiteka PTAL, lets get this merged so we can get QE playing with it.

**Comment by rhatdan** [comment]
@baude @aweiteka @giuseppe PTAL

**Comment by baude** [comment]
LGTM

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Comment by aweiteka** [comment]
cc @stefwalter dbus interface for signing and managing system trust.

**Comment by stefwalter** [comment]
@larskarlitski This is the DBus interface you're going to be using to implement the scan UI. Would you have a chance to provide feedback, make sure it does what you need it to?

**Pull request closed without merging**
