### PR TITLE
Atomic/install.py: Don't write the install data if the install fails

### PR DESCRIPTION
**Pull request by baude**
## Description
A bug was reported in issue #1022 where if the atomic install data failed,
the installation data was still written allowing the user to proceed
with an atomic run.

## Related Issue Numbers
- #1022 
-

## Pull Request Checklist:

If your Pull request contains new features or functions, tests are required. If the PR is a bug fix and no tests exist, please consider adding some to prevent regressions.
- [ ] Unittests
- [ ] Integration Tests

### CODE REVIEW

**Comment by baude** [comment]
@miabbott mind verifying before we merge ?

**Comment by miabbott** [comment]
This didn't appear to work for me:

```
# ./atomic install registry.fedoraproject.org/f25/cockpit
/usr/bin/docker run --rm --privileged -v /:/host registry.fedoraproject.org/f25/cockpit /container/atomic-install
cockpit-run: cockpit-bridge must be installed in the host

# echo $?
1
# ./atomic run registry.fedoraproject.org/f25/cockpit
/usr/bin/docker run -d --privileged --pid=host -v /:/host registry.fedoraproject.org/f25/cockpit /container/atomic-run --local-ssh

This container uses privileged security switches:

INFO: --pid=host 
      Processes in this container can see and interact with all processes on the host and disables SELinux within the container.

INFO: --privileged 
      This container runs without separation and should be considered the same as root on your system.

For more information on these switches and their security implications, consult the manpage for 'docker run'.

9d5188747bb25703b933a0abc73c7078fa95e20190e3af2373e9db4e968f3d45
# git rev-parse HEAD
90fc6c9c18370c32f14a514f414ec23d6d9bdf68
```

**Comment by miabbott** [comment]
Re-tested on a fresh VM and was unable to reproduce the error above.  I believe I had stale install data on the Vagrant box I originally used.

Looks good to merge now!

**Comment by baude** [comment]
@rh-atomic-bot bot, retest this please.

**Comment by baude** [comment]
bot, retest this please

**Comment by baude** [comment]
bot, retest this please

**Comment by baude** [comment]
@rh-atomic-bot r+ 7ca4e48

**Pull request closed without merging**
