### PR TITLE
[merged] bash: fix bash completion for system containers

### PR DESCRIPTION
**Pull request by giuseppe**
Support also mount and scan

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by giuseppe** [comment]
@yuqi-zhang can you please verify if it fixes autocompletion for you?

**Comment by yuqi-zhang** [comment]
Yep, everything looks good on my end!

**Comment by giuseppe** [comment]
@yuqi-zhang thanks for reviewing it, I have renamed the PR

**Comment by yuqi-zhang** [comment]
Just to leave here as a note, once "atomic ps" expands functionality, that probably should be used to parse auto-complete instead of the folder name magic we do now.

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
