### PR TITLE
containers: add runtime information

### PR DESCRIPTION
**Pull request by giuseppe**
complete the previous patch and make a difference between storage and
runtime.

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
Any idea why the cloud instances are blowing up?

**Comment by giuseppe** [comment]
is gomtree not available there?

**Comment by baude** [comment]
the gomtree isnt new enough...i started this with lsm yesterday

**Comment by giuseppe** [comment]
is this patch fine?

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Comment by rhatdan** [comment]
@giuseppe seems the bot is not working.  I am fine with merging this but we need the bot to run.  @jlebon Could you check what is going on?

**Comment by jlebon** [comment]
There is a bug currently in homu which makes it not understand the shorthand `r+`: https://github.com/servo/homu/issues/86. Try specifying the full commit, e.g.:

@rh-atomic-bot r+ 8ae1ab2

**Pull request closed without merging**
