### PR TITLE
[merged] dbus Integration

### PR DESCRIPTION
**Pull request by rhatdan**

### CODE REVIEW

**Comment by rhatdan** [comment]
@aweiteka could you take a look at my changes under trust.py. Basically changing to work with dbus interface.

**Comment by rhatdan** [comment]
@baude PTAL this will fix dbus to actually work.  I have not turned on all of the testing, since they don't work yet.  But currently no integration tests are firing.

**Comment by baude** [comment]
LGTM

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Comment by rhatdan** [comment]
@rh-atomic-bot retest

**Comment by rhatdan** [comment]
@rh-atomic-bot retry

**Comment by cgwalters** [comment]
Regression issue: https://github.com/projectatomic/atomic/issues/730

**Pull request closed without merging**
