### PR TITLE
Make pylint scan all the python files and fix pylint issues

### PR DESCRIPTION
**Pull request by jlebon**
The `pylint` invocation in the `Makefile` was only scanning the `atomic` file. We now make it scan all the python files. The following commits fix all the new issues that `pylint` detected.

The final commit fixes the way `rpm-ostree` args are passed to avoid a TypeError during runtime.

### CODE REVIEW

**Comment by jlebon** [comment]
@cgwalters For some reason, the `pylint` commit is still listed as the first one here, but on the branch itself (https://github.com/jlebon/atomic/commits/pylint-fixes2), it's the latest commit. Might just be a UI issue with GitHub.

I tweaked the `len(args)` issue you raised in the original PR.

**Comment by cgwalters** [comment]
LGTM!

**Comment by cgwalters** [comment]
@rhatdan ?

**Comment by jlebon** [comment]
Ahh, apparently GitHub just lists them in chronological order, not parent --> child order: https://help.github.com/articles/why-are-my-commits-in-the-wrong-order/

**Comment by jlebon** [comment]
**NOW** the `len(args)` issue is there. :)

**Comment by rhatdan** [comment]
Thanks, this is great.

LGTM

**Comment by jlebon** [comment]
Test comment, please disregard.

**Pull request merged**
