### PR TITLE
Stop ignoring API errors at low level

### PR DESCRIPTION
**Pull request by rhatdan**

### CODE REVIEW

**Comment by rhatdan** [comment]
This should fix https://github.com/projectatomic/atomic/issues/312

**Comment by baude** [comment]
@rhatdan before you merge this, can we talk on irc or bluejeans?  This will break some other functions and I think we should hammer out an alternative.

**Comment by rhatdan** [comment]
Sure

**Comment by jlebon** [comment]
This is causing the following failures in the testsuite:

```
==== ./tests/integration/test_diff.sh ====
+ set -euo pipefail
+ IFS='
	'
+ trap teardown EXIT
+ setup
+ IMAGE=atomic-test-1
++ /usr/bin/docker create atomic-test-1 /bin/true
+ id1=56c4aa704eb19458930e9cd1e3e3556acd77534a69f6f73c26013a4469e2764a
++ /usr/bin/docker create atomic-test-1 rpm -e vim-minimal
+ id2=4fb468058fd1f92aad2a4daad5a43239d53bcb65a42405247db817b1720d8b2b
+ /usr/bin/docker start 4fb468058fd1f92aad2a4daad5a43239d53bcb65a42405247db817b1720d8b2b
4fb468058fd1f92aad2a4daad5a43239d53bcb65a42405247db817b1720d8b2b
++ /bin/true
+ OUTPUT=
+ /usr/bin/coverage run --source=./Atomic/ --branch --append atomic diff -r -v 56c4aa704eb19458930e9cd1e3e3556acd77534a69f6f73c26013a4469e2764a 4fb468058fd1f92aad2a4daad5a43239d53bcb65a42405247db817b1720d8b2b
404 Client Error: Not Found ("No such image: 56c4aa704eb19458930e9cd1e3e3556acd77534a69f6f73c26013a4469e2764a")

==== ./tests/integration/test_display.sh ====
+ set -euo pipefail
+ IFS='
	'
+ ATOMIC='/usr/bin/coverage
run
--source=./Atomic/
--branch
--append
atomic'
+ DOCKER=/usr/bin/docker
+ TNAME=test_display
+ trap teardown EXIT
++ xargs
++ sed 's/ --user [0-9]*:[0-9]* / /'
++ /usr/bin/coverage run --source=./Atomic/ --branch --append atomic run --display -n TEST1 atomic-test-1
404 Client Error: Not Found ("no such id: TEST1")
```

Seems like we're using `except docker.errors.APIError` as a way to check if something can be parsed as a valid image.

**Comment by rhatdan** [comment]
https://github.com/projectatomic/atomic/pull/321 fixes this issue.

**Pull request closed without merging**
