### PR TITLE
Add instructions on how to inject custom environment variables into a…

### PR DESCRIPTION
**Pull request by metmajer**
… container.

## Description

Describes how to provide custom environment variables into a container.

## Related Issue Numbers
- https://github.com/projectatomic/atomic/issues/1051

## Pull Request Checklist:

If your Pull request contains new features or functions, tests are required. If the PR is a bug fix and no tests exist, please consider adding some to prevent regressions.
- [ ] Unittests
- [ ] Integration Tests

### CODE REVIEW

**Comment by rhatdan** [comment]
bot, add author to whitelist

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
@rh-atomic-bot r+ https://github.com/projectatomic/atomic/pull/1053/commits/e2a523112c8ab6c2a2b3817d88ff41b2ebb95094
THanks.

**Comment by metmajer** [comment]
@rhatdan do you want to re-run the checks? looks like a transient problem

**Comment by rhatdan** [comment]
@rh-atomic-bot  retry

**Comment by rhatdan** [comment]
@rh-atomic-bot r+ e2a5231

**Pull request closed without merging**
