### PR TITLE
[merged] Code cleanup for atomic sign

### PR DESCRIPTION
**Pull request by rhatdan**
We need to default the gnukeyring to the users login directory. To
make it easier for the user.

Also add bash completions for -g option

### CODE REVIEW

**Comment by rhatdan** [comment]
@baude @aweiteka PTAL

**Comment by baude** [comment]
Whats happens if the gpg is owned by root/sudo?

**Comment by rhatdan** [comment]
The the user could specify it or put it in atomic.conf.  The most common path, I believe is the users gnugpg will be in the users homedir, so we should default to that.

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
