### PR TITLE
[merged] Remove --force option and use --assumeyes

### PR DESCRIPTION
**Pull request by rhatdan**
atomic images delete --force

Should force the remove of images that are in use, not answer the prompt yes.

atomic -y|--assumeyes images delete foobar

Should force the answer to yes

Also lots of cleanups of the man page.

### CODE REVIEW

**Comment by rhatdan** [comment]
@shishir-a412ed @jwhonce PTAL

**Comment by jwhonce** [comment]
LGTM :+1:

**Comment by shishir-a412ed** [comment]
@rhatdan It is still asking me with a prompt `Do you wish to delete ['fedora']? (y/N) `

My setup:
Images: fedora
Container: 1 container based on fedora image.

When I do `atomic images delete -f fedora` I am expecting it to just delete the image `fedora` (something similar to `docker rmi -f fedora`). However I am getting the above prompt.
Is this expected behavior ?

Shishir

**Comment by rhatdan** [comment]
@shishir-a412ed 
```
atomic images delete -f fedora
```
Does a force image removal, same as docker rmi -f fedora
Thats what this change is about.

Assume yes is a atomic option.

```
atomic -y images delete fedora
```
Is the syntax I am proposing here.  This is based on the way dnf/yum work
dnf -y update ...

**Comment by shishir-a412ed** [comment]
@rhatdan Thanks for the explanation.
LGTM.

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
