### PR TITLE
[merged] constrain registry type choices for push

### PR DESCRIPTION
**Pull request by aweiteka**

### CODE REVIEW

**Comment by rhatdan** [comment]
Fix man page, Bash Completions.

**Comment by baude** [comment]
LGTM, good change.

**Comment by aweiteka** [comment]
> Fix man page

Done

> Bash Completions.

@rhatdan I think we have them: https://github.com/projectatomic/atomic/blob/master/bash/atomic#L367

**Comment by rhatdan** [comment]
Great

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
