### PR TITLE
Improve scan out and common input parsing

### PR DESCRIPTION
**Pull request by baude**
When an atomic scan is called without --detail, we print the name
    of the container or image if that is provided.  Prior, we only
    printed the first 12 characters of the image or container ID.  We
    also no dynamically size the left-most column of the output, which
    can accomodate various lengths of the image or container names.

    Created a common input parser for when the user input.  So if a
    user inputs a partial name, we attempt to discern the actual
    container or image being referenced.  The were three definitions
    added; _is_container, _is_image, and a wrapper function for both
    called get_input_id.  If either function can make a match to the
    input identifier, it returns the image or container ID.

    And lastly, to reduce the number of calls (queries) into docker,
    there are now stub functions that should be called instead.
    These stub functions are self-explainatory by their names, which
    are: get_images, get_containers, and get_active_containers.

### CODE REVIEW

**Comment by baude** [comment]
An example of the formatting change:

```
[bbaude@localhost atomic]$ sudo ./atomic scan rhel rhel6:latest

Scanning...

Container/Image   Cri   Imp   Med   Low  
---------------   ---   ---   ---   ---  
rhel              1     5     15    1    
rhel6:latest      0     0     2     0 
```

And another example with long and variable lengths to the inputs.  Note that one image exceeds a maximum column width and is shortened to fit with preceding ellipses.
```
[bbaude@localhost atomic]$ sudo ./atomic scan registry.access.redhat.com/rhel7/rsyslog registry.access.redhat.com/rhel7/rpmostree-toolbox-lorax rhel

Scanning...

Container/Image                                      Cri   Imp   Med   Low  
--------------------------------------------------   ---   ---   ---   ---  
...access.redhat.com/rhel7/rpmostree-toolbox-lorax   0     0     0     0    
rhel                                                 1     5     15    1    
registry.access.redhat.com/rhel7/rsyslog             0     0     0     0    
```

**Comment by baude** [comment]
An example of input parsing to help users with 'atomic stop'.  

```
[bbaude@localhost atomic]$ docker ps 
CONTAINER ID        IMAGE               COMMAND               CREATED             STATUS              PORTS               NAMES
1d9f73903ea0        10acc               "/bin/bash"           16 minutes ago      Up 16 minutes                           silly
2eb5cc91d77f        bef54               "/bin/bash"           19 minutes ago      Up 19 minutes                           silly_dog
489b9dd81ac0        bef54               "/bin/bash"           19 minutes ago      Up 19 minutes                           silly_rabbit
b92abbb3dea5        openscap-daemon     "/bin/sh -c oscapd"   21 minutes ago      Up 21 minutes                           high_lalande

```
Note here we have four containers running, three of which have a common name, as they begin with 'silly'

```
[bbaude@localhost atomic]$ sudo ./atomic stop silly
```
Note the above command worked because there was an exact match for 'silly'.  Now if we re-run the command again, it fails with an error

```
[bbaude@localhost atomic]$ sudo ./atomic stop silly
Multiple matches were found for silly. Refine your search to narrow results.
```

And an example using atomic scan:
```
[bbaude@localhost atomic]$ sudo ./atomic scan rhel7
Found more than one image possibly matching 'rhel7'. They are:
    registry.access.stage.redhat.com/rhel7/rhel:latest
    registry.access.redhat.com/rhel7:latest
    registry.access.stage.redhat.com/rhel7/rhel:7.1-4
    registry.access.redhat.com/rhel7:7.1-4
    docker.io/richxsl/rhel7:latest
    redhat/rhel7:0
    redhat/rhel7:0-23
    redhat/rhel7:latest 
Refine your search to narrow results.
```

**Comment by rhatdan** [comment]
This is not applying to the master branch.

**Comment by rhatdan** [comment]
Rebase please.

**Comment by baude** [comment]
@rhatdan better now ?

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
