### PR TITLE
Suppress STDOUT of lower level commands e.g. vgreduce, wipefs.

### PR DESCRIPTION
**Pull request by shishir-a412ed**
Signed-off-by: Shishir Mahajan <shishir.mahajan@redhat.com>

### CODE REVIEW

**Comment by shishir-a412ed** [comment]
Right now when I do: `atomic storage modify --remove-device /dev/vdb`. I see this output.
 
````
Removed "/dev/vdb1" from volume group "fedora"
/dev/vdb: 2 bytes were erased at offset 0x000001fe (dos): 55 aa
/dev/vdb: calling ioctl to re-read partition table: Success
````

This patch suppresses the lower level commands output.

ping @rhatdan

**Comment by sghosh151** [comment]
Log it with meta information about the action rather than suppressing it and missing occasionally important stuff

**Comment by rhatdan** [comment]
I kind of like that output. Why do you want to remove it?

**Comment by shishir-a412ed** [comment]
@rhatdan My thought was If I am running 
````
$$ atomic storage modify --remove-device /dev/vdb. 
````
I would just like to see if my device `/dev/vdb` was removed successfully or not. On a successful run. OUTPUT: `/dev/vdb removed successfully` should be enough for a user.

Ofcourse if there is an error, more information is helpful for debugging.

I just felt for a user (On a successful run of the command): 
a) If device signatures were wiped out properly or not.
b) If device partition table was updated and re-read by ioctl 
    would be too much information since the command was successful anways.

Let me know if you feel differently and I can close this PR.

Shishir

**Comment by baude** [comment]
@shishir-a412ed How would you feel about having that information be put into a bytestring where on failure, it would be spit out ?

**Comment by shishir-a412ed** [comment]
@baude PTAL.

Now on success, there will be no output message. {Same as `atomic storage modify --add-device /dev/vdb`}. When `--add-device` is successful, there is no output message, just a return code 0. This patch would exhibit same behavior for `--remove-device`.

In case of an error it would look something like this: (For testing purposes I changed the volume group name to `atomicos` {atomicos does not exist, my VG name is fedora}  to generate an error)

````
sh-4.4# atomic storage modify --remove-device /dev/vdb 
Return Code: 5
Failure: b'  Volume group "atomicos" not found\n  Cannot process volume group atomicos\n  Volume group "atomicos" not found\n  Cannot process volume group atomicos\n  Failed to find physical volume "/dev/vdb1".\n'
atomic storage modify --remove-device failed
````

**Comment by shishir-a412ed** [comment]
@baude Any updates on this one ?

**Comment by baude** [comment]
LGTM but @rhatdan  has the final call.

**Comment by shishir-a412ed** [comment]
@baude :) thanks ! .... Will wait for his input.

**Comment by rhatdan** [comment]
@rh-atomic-bot r+ 6be9adf

**Pull request closed without merging**
