### PR TITLE
[merged] atomic: use fully qualified image names to Skopeo

### PR DESCRIPTION
**Pull request by giuseppe**
Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@runcom PTAL

**Comment by runcom** [comment]
@giuseppe why is this needed now? (I don't know the context)

**Comment by giuseppe** [comment]
@runcom it is needed to close https://bugzilla.redhat.com/show_bug.cgi?id=1346929

It is the same logic used by "atomic info --remote"

**Comment by runcom** [comment]
fine, LGTM /cc @baude

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
