### PR TITLE
[merged] Change options to the agreed syntax.

### PR DESCRIPTION
**Pull request by rhatdan**
We agreed on using --sign-by for specifying the signer, and --directory
to specify the output directory for images.

### CODE REVIEW

**Comment by rhatdan** [comment]
@baude @mtrmac @aweiteka PTAL

**Comment by mtrmac** [comment]
ACK.

(I still have concerns about the configuration capabilities and the default, but those are unchanged by this PR and I will raise them separately.)

**Comment by baude** [comment]
The reason I deviated from the "agreed" options was because after further consideration, it seemed the options were still insufficient.  In this implementation, while you can influence the directory the signature lands in, you cannot influence the signature's name.  So it will be signature-integer.

In the example we used, you had liked the idea of:
```
atomic sign -o busybox.sig -d /tmp
```
resulting in /tmp/busybox.sig.

If this approach is your preference, I'm ok with it.

**Comment by rhatdan** [comment]
My problem with the -n busybox.sig is, what does the user do with it.  Since the atomic tool will have know way of finding it.  I believe @aweiteka pointed out that you could just do 

```
atomic sign -d /tmp/sigs
cd /tmp/sigs
tar zcvf /tmp/sigs.tgz .
scp /tmp/sigs.tgz root@signature.example.com
ssh root@signature.example.com sh -c "cd /var/www/html; tar xvf ~/sigs.tgz"
```

**Comment by mtrmac** [comment]
> My problem with the -n busybox.sig is, what does the user do with it.

With `-o` (full path to a single destination file), some possible future equivalent of `koji import-sig`. We have designed this to be served from a static web server but it doesn’t _have_ to be done that way. Of course we don’t have a known user for any other way right now.

For `-n` (use the standard directory structure but a different name for the image), this would allow a workflow where an image is created under a `prerelease` repo and then copied into the `released` repo when QA is done, and `atomic sign -n released prerelease` could be used to prepare the signatures before actually pushing the image into the `released` Docker registry (so that at no moment in time there is a `released` image with missing signatures).

Really, none of `-o`, `-n` and `-d` is essential.

**Comment by mtrmac** [comment]
> The reason I deviated from the "agreed" options was because after further consideration, it seemed the options were still insufficient.

@baude , looking at https://github.com/projectatomic/atomic/pull/539/files#diff-4a7d85c2a2907162beed01286a2149b3R52 , AFAICS the current `-o` implements the “root directory” semantics, not the “output file” semantics, and this PR is only changing the option naming. Am I missing anything?

**Comment by rhatdan** [comment]
Ok I am going to merge and then we can revisit with these options when demand arises. 
@rh-atomic-bot r+

**Pull request closed without merging**
