### PR TITLE
[merged] Fix handling of args for host.py

### PR DESCRIPTION
**Pull request by rhatdan**

### CODE REVIEW

**Comment by rhatdan** [comment]
Should fix https://github.com/projectatomic/atomic/issues/725

**Comment by rhatdan** [comment]
@cgwalters @miabbott PTAL

**Comment by miabbott** [comment]
Pulled the PR on a CAHC system and worked fine there.  :+1:

**Comment by cgwalters** [comment]
@rh-atomic-bot r+ 2d59c8c

**Pull request closed without merging**
