### PR TITLE
Make git_images always return a list.

### PR DESCRIPTION
**Pull request by rhatdan**
I would prefer this pull request to https://github.com/projectatomic/atomic/pull/260

Basically we want get_images to always return a list, and if the list is empty to display nothing on an

atomic images list 

command.

### CODE REVIEW

**Comment by rhatdan** [comment]
@bexelbie https://github.com/chuanchang PTAL

**Comment by bexelbie** [comment]
@rhatdan because `docker images` returns headers in the zero image case, I think we should too.

**Comment by bexelbie** [comment]
Reading the code again, I believe the code in #276 is a situation where there is always a list being passed.  If it isn't, I need a more clear guidepost to where it isn't.  The big change that #276 introduced was to ensure we always had a length for the formatting.  It defaults to 1 which means the empty list just displays headers and exits.

**Comment by rhatdan** [comment]
I actually think docker images returningin NULL is wrong, and we have other places in the code where we do not check the code.

for i in self.get_images() 

For example.

**Comment by rhatdan** [comment]
@baude @cgwalters PTAL

**Comment by cgwalters** [comment]
The test is failing due to a syntax error.

**Comment by rhatdan** [comment]
@cgwalters Fixed.

**Comment by rhatdan** [comment]
@bexelbie @baude @cgwalters PTAL

Atomic migrate is failing, but unrelated to this patch.

**Comment by baude** [comment]
@rhatdan this looks good.  makes sense

**Pull request merged**
