### PR TITLE
use NAME and IMAGE variables, not literals in README.md

### PR DESCRIPTION
**Pull request by ibotty**
I assume that is a typo and not some magic that escapes me.

### CODE REVIEW

**Comment by rhatdan** [comment]
Why didn't you add IMAGE=${IMAGE}

Also don't we need to escape all of these.

IMAGE=\${IMAGE}

**Comment by ibotty** [comment]
> Why didn't you add IMAGE=${IMAGE}

because I missed it. :-|

If we need to escape them, don't we need to escape all environment variables in LABELs? I don't really understand how substitution in LABELs is supposed to work. Is `NAME=NAME` supposed to be `NAME=my_image_name` when used or `my_image_name=my_image_name`. If the latter, how can one supply a `NAME=my_image_name`?

**Comment by rhatdan** [comment]
NAME=my_image_name

**Comment by ibotty** [comment]
I am not entirely sure my patch is correct. testing it, it substitutes NAME=NAME (i.e. without any `$`) and IMAGE=IMAGE correctly, so that part is at least unnecessary. I don't get any expanded $LOG_DIR regardless of escaping it though. (using atomic-0-0.7.gita7ff4cb.fc22.x86_64).

**Comment by rhatdan** [comment]
Yes we will continue to support NAME=NAME and IMAGE=IMAGE ,but I think we should move docs to talk about ${IMAGE}.

$LOG_DIR  should be $LOGDIR

**Pull request merged**
