### PR TITLE
[merged] More cleanup for dbus interfaces

### PR DESCRIPTION
**Pull request by rhatdan**

### CODE REVIEW

**Comment by rhatdan** [comment]
@jlebon I need these packages added for the dbus tests to pass.

python3-slip-dbus-0.6.4-4.fc25.noarch
python-slip-0.6.4-4.fc25.noarch
python3-slip-0.6.4-4.fc25.noarch
python-slip-dbus-0.6.4-4.fc25.noarch

Is there some way I can do this automatically?

**Comment by cgwalters** [comment]
First, all build dependencies should go into the Fedora spec file first, which will ensure [CAHC](https://wiki.centos.org/SpecialInterestGroup/Atomic/Devel) works.

Second, they can be added to the `.redhat-ci.yml` file.  However doing that will conflict with https://github.com/projectatomic/atomic/pull/724 - can we land that first?

**Comment by rhatdan** [comment]
I agree with updating the spec file, but I want to make sure all of the tests pass jenkins. 
The other patch can be merged by you guys.  I was waiting for @cgwalters  and @jlebon to agree on that one.

**Comment by jlebon** [comment]
Yup, will look into #724 today.

**Comment by rhatdan** [comment]
Ok I removed the tests for now, so that I can get these checks in, I will ask @lsm5 to add requires for python3-slip-dbus and python-slip-dbus to atomic-1.13.3 build.

@baude @ddarah PTAL

**Comment by ddarrah** [comment]
@rhatdan LGTM

**Comment by jlebon** [comment]
@rhatdan You can add temporary reqs to the Dockerfile (used for pylint, build, and install) and/or the YAML (used for unit & integration tests) as needed. Once the atomic packages with the updated spec make it into the various distros, we can then take back them out (in the case of CAHC, pretty much immediately).

**Comment by rhatdan** [comment]
@jlebon Thanks, The tests are not all working yet, so I can wait.  But I want to get these changes in for todays build.
@rh-atomic-bot r+

**Pull request closed without merging**
