### PR TITLE
Separator in syscontainer name

### PR DESCRIPTION
**Pull request by eyusupov**
## Description
The old code was parsing postgres:9.6 as (postgres:9.6, postgres, 9:6).
This issue fixed by reusing `util.Decompose`.

## Related Bugzillas
n/a

## Related Issue Numbers
n/a

## Pull Request Checklist:

If your Pull request contains new features or functions, tests are required. If the PR is a bug fix and no tests exist, please consider adding some to prevent regressions.
- [x] Unittests
- [ ] Integration Tests

### CODE REVIEW

**Comment by eyusupov** [comment]
Created instead of #1205, because CI was not working there

**Comment by giuseppe** [comment]
no luck, the CI seems broken:

/cc @jlebon

**Comment by jlebon** [comment]
bot, retest this please

**Comment by giuseppe** [comment]
bot, retest this please

**Comment by ashcrow** [comment]
Flake?

**Comment by giuseppe** [comment]
yes, but now it looks happy again :-) so I ready to pull the trigger:

@rh-atomic-bot r+ ffcf416

**Comment by eyusupov** [comment]
Just going to squash the fixup commit

**Comment by eyusupov** [comment]
Nevermind, it was autosquashed by the bot :+1:

**Pull request closed without merging**
