### PR TITLE
Add version support for atomic command

### PR DESCRIPTION
**Pull request by rhatdan**

### CODE REVIEW

**Comment by rhatdan** [comment]
@willmtemple @lsm5 @bexelbie @cgwalters could you take a quick look at this?

@cgwalters Any good idea of how we could have setup.py modify the content that atomic -v shows?

**Comment by lsm5** [comment]
`atomic -v` and `atomic --version` give me `1.1`

**Comment by rhatdan** [comment]
@lsm5 They are supposed to, this is current version of atomic in github.  We will update this for the next release for RHEL

**Comment by lsm5** [comment]
ah yup, i meant lgtm :) ... i'll add this for fedora and centos, sometime after today, rel-eng seems to have some trouble pushing updates :|

**Pull request merged**
