### PR TITLE
We need to pass then entire environment into executed command

### PR DESCRIPTION
**Pull request by rhatdan**

### CODE REVIEW

**Comment by rhatdan** [comment]
The goal is to fix the issues discussed in https://github.com/projectatomic/atomic/pull/158

**Comment by rhatdan** [comment]
@bexelbie @sctweedie @baude PTAL

@vpavlin @praiskup if this gets merged can I close the other pull request?

**Comment by praiskup** [comment]
On Friday 11 of September 2015 08:34:51 Daniel J Walsh wrote:
> @vpavlin @praiskup if this gets merged can I close the other pull request?

+1

**Comment by vpavlin** [comment]
I think so

**Pull request merged**
