### PR TITLE
papr.sh: use Fedora 28

### PR DESCRIPTION
**Pull request by giuseppe**
Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM but failing tests.

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests

**Comment by giuseppe** [comment]
I added a test to verify if "skopeo copy" can be used with ostree so now tests are happy.  This is to prevent tests to run with a broken version of Skopeo.

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
