### PR TITLE
Add base integration test for dbus

### PR DESCRIPTION
**Pull request by baude**
Define the methodology for testing dbus in integrations tests.  Using a decorator,
this allows us to automatically define and test dbus tests. This is only the base
test to exercise the testing.

### CODE REVIEW

**Comment by rhatdan** [comment]
All tests are failing?

**Comment by baude** [comment]
@rhatdan let's merge this.  It's safe now with the try/except skip clauses added to the test.

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Comment by rhatdan** [comment]
@rh-atomic-bot r=rhatdan 6ee7dac

**Pull request closed without merging**
