### PR TITLE
[merged] Don't call sub_env_strings twice

### PR DESCRIPTION
**Pull request by rhatdan**
Also remove useless check on display

### CODE REVIEW

**Comment by rhatdan** [comment]
This fixes https://github.com/projectatomic/atomic/issues/540

**Comment by rhatdan** [comment]
@adelton PTAL

**Comment by adelton** [comment]
Let me try to find some reproducer, so that we could also add tests for that.

**Comment by adelton** [comment]
This change LGTM and useful but it does not really fix https://github.com/projectatomic/atomic/issues/540.

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
